import { StyleSheet } from 'react-native';
import { lightColors } from '../../constants/Theme';
import Fonts from '../../constants/Fonts';
export const createStyles = (colors) => StyleSheet.create({
    mainContainer: {
        flex: 1,
        backgroundColor: colors.backgroundColor,
    },
    header: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 20,
        paddingVertical: 16,
    },
    backButton: {
        width: 44,
        height: 44,
        borderRadius: 22,
        backgroundColor: colors.btnBackgroundColor,
        alignItems: 'center',
        justifyContent: 'center',
    },
    headerTitle: Object.assign(Object.assign({}, Fonts.medium18), { color: colors.mainTextColor }),
    headerSpacer: {
        width: 44,
        height: 44,
    },
    notificationButton: {
        width: 44,
        height: 44,
        borderRadius: 22,
        backgroundColor: colors.btnBackgroundColor,
        alignItems: 'center',
        justifyContent: 'center',
    },
    scrollContent: {
        paddingHorizontal: 20,
        flexGrow: 1,
    },
    sectionTitle: Object.assign(Object.assign({}, Fonts.medium18), { color: colors.mainTextColor }),
    detailsCard: {
        backgroundColor: colors.backgroundColor,
        borderRadius: 10,
        padding: 16,
        borderWidth: 0.5,
        borderColor: colors.lightGrayColor,
        gap: 16,
    },
    detailRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        gap: 12,
    },
    detailLabel: Object.assign(Object.assign({}, Fonts.regular14), { color: colors.subTextColor }),
    detailValue: Object.assign(Object.assign({}, Fonts.medium14), { color: colors.mainTextColor, flex: 1, textAlign: 'right' }),
    divider: {
        height: 1,
        backgroundColor: colors.lightGrayColor,
    },
    eventChipsContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 15,
    },
    eventChip: {
        backgroundColor: '#EBEBEB',
        borderRadius: 6,
        paddingHorizontal: 10,
        height: 32,
        width: 70,
        alignItems: 'center',
        justifyContent: 'center',
    },
    eventChipText: Object.assign(Object.assign({}, Fonts.regular12), { color: '#777777' }),
    bottomButtons: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        gap: 20,
    },
    cancelButton: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: colors.backgroundColor,
        borderRadius: 10,
        height: 54,
        gap: 8,
        borderWidth: 0.5,
        borderColor: colors.lightGrayColor,
    },
    cancelButtonText: Object.assign(Object.assign({}, Fonts.medium16), { color: colors.subTextColor }),
    confirmButton: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: colors.primaryColor,
        borderRadius: 10,
        height: 54,
        gap: 8,
    },
    confirmButtonText: Object.assign(Object.assign({}, Fonts.medium16), { color: colors.whiteColor }),
    errorText: Object.assign(Object.assign({}, Fonts.regular13), { color: '#E11D48', textAlign: 'center' }),
    feedbackOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0,0,0,0.45)',
        justifyContent: 'flex-end',
        paddingHorizontal: 20,
        paddingBottom: 28,
    },
    feedbackSheet: {
        backgroundColor: colors.backgroundColor,
        borderRadius: 20,
        padding: 20,
        gap: 12,
        borderWidth: 0.5,
        borderColor: colors.lightGrayColor,
    },
    feedbackTitle: Object.assign(Object.assign({}, Fonts.medium18), { color: colors.mainTextColor, textAlign: 'center' }),
    feedbackBody: Object.assign(Object.assign({}, Fonts.regular14), { color: colors.subTextColor, textAlign: 'center', lineHeight: 20 }),
    feedbackPrimaryButton: {
        height: 48,
        borderRadius: 12,
        backgroundColor: colors.primaryColor,
        alignItems: 'center',
        justifyContent: 'center',
        marginTop: 4,
    },
    feedbackPrimaryButtonText: Object.assign(Object.assign({}, Fonts.medium14), { color: colors.whiteColor }),
    emptyState: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
        paddingHorizontal: 24,
    },
    emptyStateTitle: Object.assign(Object.assign({}, Fonts.medium18), { color: colors.mainTextColor }),
    emptyStateBody: Object.assign(Object.assign({}, Fonts.regular14), { color: colors.subTextColor, textAlign: 'center', marginTop: 8 }),
});
const Styles = createStyles(lightColors);
export default Styles;
