import { StyleSheet } from 'react-native';
import { ThemeColors, lightColors } from '../../constants/Theme';
import Fonts from '../../constants/Fonts';

export const createStyles = (colors: ThemeColors) => StyleSheet.create({
    mainContainer: {
        flex: 1,
        backgroundColor: colors.whiteColor,
    },
    header: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 20,
        paddingVertical: 16,
    },
    backButton: {
        width: 44,
        height: 44,
        borderRadius: 22,
        backgroundColor: '#F5F5F5',
        alignItems: 'center',
        justifyContent: 'center',
    },
    headerTitle: {
        ...Fonts.medium18,
        color: colors.mainTextColor,
    },
    notificationButton: {
        width: 44,
        height: 44,
        borderRadius: 22,
        backgroundColor: '#F5F5F5',
        alignItems: 'center',
        justifyContent: 'center',
    },
    scrollContent: {
        paddingHorizontal: 20,
        flexGrow: 1,
    },
    sectionTitle: {
        ...Fonts.medium18,
        color: colors.mainTextColor,
    },
    eventDetailsCard: {
        backgroundColor: colors.whiteColor,
        borderRadius: 10,
        padding: 16,
        borderWidth: 0.5,
        borderColor: '#DEDEDE',
        gap: 16,
    },
    detailRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    detailLabel: {
        ...Fonts.regular14,
        color: '#9B9F9F',
    },
    detailValue: {
        ...Fonts.medium14,
        color: colors.mainTextColor,
    },
    divider: {
        height: 1,
        backgroundColor: '#DEDEDE',
    },
    descriptionText: {
        ...Fonts.regular13,
        color: '#9B9F9F',
        lineHeight: 20,
    },
    inputLabel: {
        ...Fonts.medium14,
        color: colors.mainTextColor,
    },
    inputLabelBold: {
        ...Fonts.semibold14,
        color: colors.mainTextColor,
    },
    eventsInputContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#F7FAFF',
        borderRadius: 10,
        paddingHorizontal: 12,
        paddingVertical: 10,
        borderWidth: 0.5,
        borderColor: '#E0ECFE',
        gap: 10,
    },
    eventChipsContainer: {
        flexDirection: 'row',
        flex: 1,
        flexWrap: 'wrap',
        alignItems: 'center',
        gap: 10,
    },
    eventChip: {
        backgroundColor: '#EBEBEB',
        borderRadius: 16,
        paddingHorizontal: 10,
        height: 30,
        alignItems: 'center',
        justifyContent: 'center',
        flexDirection: 'row',
        gap: 6,
    },
    eventChipText: {
        ...Fonts.regular12,
        color: '#777777',
    },
    addEventIconButton: {
        width: 34,
        height: 34,
        alignItems: 'center',
        justifyContent: 'center',
        borderRadius: 10,
        backgroundColor: colors.whiteColor,
        borderWidth: 0.5,
        borderColor: '#E0ECFE',
    },
    eventPicker: {
        marginTop: 12,
        backgroundColor: colors.whiteColor,
        borderWidth: 0.5,
        borderColor: '#E0ECFE',
        borderRadius: 12,
        padding: 12,
    },
    eventPickerTitle: {
        ...Fonts.medium14,
        color: colors.mainTextColor,
        marginBottom: 10,
    },
    eventPickerGrid: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 10,
    },
    suggestionChip: {
        backgroundColor: colors.whiteColor,
        borderRadius: 16,
        borderWidth: 0.5,
        borderColor: '#E0ECFE',
        paddingHorizontal: 12,
        height: 32,
        alignItems: 'center',
        justifyContent: 'center',
    },
    suggestionChipActive: {
        backgroundColor: colors.primaryColor,
        borderColor: colors.primaryColor,
    },
    suggestionText: {
        ...Fonts.regular12,
        color: colors.grayColor,
    },
    suggestionTextActive: {
        color: colors.whiteColor,
    },
    chestNumberInput: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#F7FAFF',
        borderRadius: 10,
        paddingHorizontal: 16,
        height: 54,
        borderWidth: 0.5,
        borderColor: '#E0ECFE',
        gap: 10,
    },
    textInput: {
        flex: 1,
        ...Fonts.regular14,
        color: colors.mainTextColor,
        padding: 0,
    },
    defaultChestRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginTop: 10,
        gap: 8,
    },
    defaultChestBox: {
        width: 18,
        height: 18,
        borderRadius: 5,
        borderWidth: 1,
        borderColor: '#D6D6D6',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: colors.whiteColor,
    },
    defaultChestBoxActive: {
        backgroundColor: '#2F6BFF',
        borderColor: '#2F6BFF',
    },
    defaultChestText: {
        ...Fonts.regular12,
        color: colors.grayColor,
    },
    bottomContainer: {
        paddingHorizontal: 20,
    },
    confirmButton: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: colors.primaryColor,
        borderRadius: 10,
        height: 54,
        gap: 8,
    },
    confirmButtonText: {
        ...Fonts.medium16,
        color: colors.whiteColor,
    },
    modalBackdrop: {
        flex: 1,
        backgroundColor: 'rgba(0,0,0,0.35)',
        alignItems: 'center',
        justifyContent: 'center',
        paddingHorizontal: 20,
    },
    modalCard: {
        width: '100%',
        backgroundColor: colors.whiteColor,
        borderRadius: 16,
        padding: 16,
    },
    modalTitle: {
        ...Fonts.medium18,
        color: colors.mainTextColor,
    },
    modalSubtitle: {
        ...Fonts.regular13,
        color: colors.grayColor,
        marginTop: 4,
        marginBottom: 12,
    },
    modalSectionTitle: {
        ...Fonts.medium14,
        color: colors.mainTextColor,
        marginTop: 12,
        marginBottom: 8,
    },
    modalSearchRow: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#F7FAFF',
        borderRadius: 10,
        paddingHorizontal: 12,
        height: 46,
        borderWidth: 0.5,
        borderColor: '#E0ECFE',
        gap: 8,
    },
    modalSearchInput: {
        flex: 1,
        ...Fonts.regular14,
        color: colors.mainTextColor,
        padding: 0,
    },
    modalChipsGrid: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 10,
    },
    modalChip: {
        backgroundColor: colors.whiteColor,
        borderRadius: 16,
        borderWidth: 0.5,
        borderColor: '#E0ECFE',
        paddingHorizontal: 12,
        height: 32,
        alignItems: 'center',
        justifyContent: 'center',
    },
    modalChipActive: {
        backgroundColor: colors.primaryColor,
        borderColor: colors.primaryColor,
    },
    modalChipText: {
        ...Fonts.regular12,
        color: colors.grayColor,
    },
    modalChipTextActive: {
        color: colors.whiteColor,
    },
    modalButtonsRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginTop: 16,
        gap: 12,
    },
    modalCancelButton: {
        flex: 1,
        height: 46,
        borderRadius: 10,
        borderWidth: 1,
        borderColor: '#E0ECFE',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: colors.whiteColor,
    },
    modalCancelText: {
        ...Fonts.medium14,
        color: colors.grayColor,
    },
    modalConfirmButton: {
        flex: 1,
        height: 46,
        borderRadius: 10,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: colors.primaryColor,
    },
    modalConfirmText: {
        ...Fonts.medium14,
        color: colors.whiteColor,
    },
});

const Styles = createStyles(lightColors);

export default Styles;
