import { StyleSheet } from 'react-native';
import Fonts from '../../constants/Fonts';
export const createStyles = (colors) => StyleSheet.create({
    mainContainer: {
        flex: 1,
        backgroundColor: colors.backgroundColor,
    },
    header: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 20,
        paddingVertical: 16,
        borderBottomWidth: 0.5,
        borderBottomColor: colors.lightGrayColor,
    },
    headerButton: {
        width: 44,
        height: 44,
        borderRadius: 22,
        backgroundColor: 'transparent',
        alignItems: 'center',
        justifyContent: 'center',
    },
    headerSpacer: {
        width: 44,
        height: 44,
    },
    headerTitle: Object.assign(Object.assign({}, Fonts.medium18), { color: colors.mainTextColor }),
    headerTitleRow: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
        paddingHorizontal: 12,
    },
    scrollContent: {
        paddingHorizontal: 20,
        paddingTop: 24,
    },
    fieldBlock: {
        marginBottom: 16,
    },
    stepHeaderRow: {
        marginBottom: 18,
        gap: 4,
    },
    stepTopRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    stepCounter: Object.assign(Object.assign({}, Fonts.regular12), { color: colors.primaryColor }),
    stepTitle: Object.assign(Object.assign({}, Fonts.semibold16), { color: colors.mainTextColor }),
    stepPreviewButton: {
        minWidth: 86,
        borderWidth: 1,
        borderColor: colors.primaryColor,
        borderRadius: 10,
        alignItems: 'center',
        justifyContent: 'center',
        paddingHorizontal: 10,
        paddingVertical: 6,
        backgroundColor: colors.cardBackground,
    },
    stepPreviewButtonDisabled: {
        opacity: 0.45,
    },
    stepPreviewText: Object.assign(Object.assign({}, Fonts.medium13), { color: colors.primaryColor }),
    skipRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 10,
    },
    skipLabel: Object.assign(Object.assign({}, Fonts.regular13), { color: colors.mainTextColor }),
    fieldLabel: Object.assign(Object.assign({}, Fonts.regular12), { color: colors.grayColor, marginBottom: 6 }),
    fieldInput: Object.assign(Object.assign({ borderWidth: 1, borderColor: colors.lightGrayColor, borderRadius: 12, paddingHorizontal: 14, paddingVertical: 15, minHeight: 54 }, Fonts.regular15), { color: colors.mainTextColor, backgroundColor: colors.btnBackgroundColor }),
    fieldInputError: {
        borderColor: '#ED5454',
    },
    readonlyField: {
        borderWidth: 1,
        borderColor: colors.lightGrayColor,
        borderRadius: 12,
        paddingHorizontal: 12,
        paddingVertical: 12,
        backgroundColor: colors.btnBackgroundColor,
    },
    readonlyText: Object.assign(Object.assign({}, Fonts.regular14), { color: colors.mainTextColor }),
    dateButton: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
        borderWidth: 1,
        borderColor: colors.lightGrayColor,
        borderRadius: 12,
        paddingHorizontal: 12,
        paddingVertical: 12,
        backgroundColor: colors.btnBackgroundColor,
    },
    dateText: Object.assign(Object.assign({}, Fonts.regular14), { color: colors.mainTextColor }),
    fieldTextarea: {
        minHeight: 160,
        textAlignVertical: 'top',
    },
    mediaHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginBottom: 10,
    },
    mediaAddButton: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
        backgroundColor: colors.primaryColor,
        borderRadius: 10,
        paddingHorizontal: 12,
        paddingVertical: 8,
    },
    mediaAddText: Object.assign(Object.assign({}, Fonts.regular12), { color: colors.pureWhite }),
    mediaGrid: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 10,
        marginBottom: 16,
    },
    mediaTile: {
        width: 88,
        height: 88,
        borderRadius: 12,
        overflow: 'hidden',
        backgroundColor: colors.btnBackgroundColor,
    },
    mediaImage: {
        width: '100%',
        height: '100%',
    },
    mediaBadge: {
        position: 'absolute',
        bottom: 6,
        right: 6,
        paddingHorizontal: 6,
        paddingVertical: 2,
        borderRadius: 6,
        backgroundColor: 'rgba(0,0,0,0.55)',
    },
    mediaBadgeText: Object.assign(Object.assign({}, Fonts.regular10), { color: colors.pureWhite }),
    mediaEmptyText: Object.assign(Object.assign({}, Fonts.regular12), { color: colors.grayColor }),
    actionRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 12,
        marginTop: 8,
    },
    saveButton: {
        flex: 1,
        backgroundColor: colors.primaryColor,
        borderRadius: 14,
        alignItems: 'center',
        justifyContent: 'center',
        minHeight: 56,
        paddingVertical: 14,
    },
    saveButtonDisabled: {
        opacity: 0.45,
    },
    saveText: Object.assign(Object.assign({}, Fonts.medium14), { color: colors.pureWhite }),
    skipSecondaryButton: {
        marginTop: 10,
        borderWidth: 1,
        borderColor: colors.lightGrayColor,
        borderRadius: 12,
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 12,
        backgroundColor: colors.cardBackground,
    },
    skipSecondaryText: Object.assign(Object.assign({}, Fonts.medium14), { color: colors.subTextColor }),
    deleteButton: {
        marginTop: 16,
        borderRadius: 12,
        backgroundColor: '#FFECEC',
        paddingVertical: 12,
        alignItems: 'center',
        flexDirection: 'row',
        justifyContent: 'center',
        gap: 8,
    },
    deleteText: Object.assign(Object.assign({}, Fonts.medium14), { color: '#ED5454' }),
    modalOverlay: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        backgroundColor: 'rgba(0,0,0,0.45)',
        justifyContent: 'center',
        paddingHorizontal: 20,
    },
    modalBackdrop: {
        position: 'absolute',
        top: 0,
        bottom: 0,
        left: 0,
        right: 0,
    },
    dateModalContainer: {
        backgroundColor: colors.cardBackground,
        borderRadius: 18,
        padding: 16,
        borderWidth: 1,
        borderColor: colors.lightGrayColor,
    },
    dateModalTitle: Object.assign(Object.assign({}, Fonts.semibold16), { color: colors.mainTextColor }),
    modalDoneButton: {
        marginTop: 12,
        borderRadius: 12,
        backgroundColor: colors.primaryColor,
        paddingVertical: 12,
        alignItems: 'center',
        justifyContent: 'center',
    },
    modalDoneButtonText: Object.assign(Object.assign({}, Fonts.semibold13), { color: colors.pureWhite }),
    eventList: {
        maxHeight: 260,
    },
    eventListContent: {
        marginTop: 10,
        gap: 8,
    },
    eventRow: {
        borderWidth: 1,
        borderColor: colors.lightGrayColor,
        borderRadius: 10,
        paddingHorizontal: 12,
        paddingVertical: 10,
        marginBottom: 8,
        backgroundColor: colors.btnBackgroundColor,
    },
    eventRowActive: {
        borderColor: colors.primaryColor,
        backgroundColor: colors.cardBackground,
    },
    eventRowText: Object.assign(Object.assign({}, Fonts.regular14), { color: colors.mainTextColor }),
    eventRowTextActive: {
        color: colors.primaryColor,
    },
    peopleChipsRow: {
        marginTop: 10,
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 8,
    },
    peopleChip: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
        borderWidth: 1,
        borderColor: colors.lightGrayColor,
        borderRadius: 999,
        paddingHorizontal: 10,
        paddingVertical: 6,
        backgroundColor: colors.btnBackgroundColor,
    },
    peopleChipText: Object.assign(Object.assign({}, Fonts.regular12), { color: colors.mainTextColor }),
    previewCard: {
        borderWidth: 1,
        borderColor: colors.lightGrayColor,
        borderRadius: 14,
        padding: 14,
        backgroundColor: colors.cardBackground,
        gap: 8,
        marginBottom: 8,
    },
    previewTitle: Object.assign(Object.assign({}, Fonts.semibold16), { color: colors.mainTextColor }),
    previewMeta: Object.assign(Object.assign({}, Fonts.regular12), { color: colors.subTextColor }),
    previewText: Object.assign(Object.assign({}, Fonts.regular14), { color: colors.mainTextColor }),
    previewMediaImage: {
        width: '100%',
        height: 220,
        borderRadius: 12,
        marginTop: 4,
        backgroundColor: colors.btnBackgroundColor,
    },
    loadingOverlay: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        backgroundColor: 'rgba(0,0,0,0.35)',
        alignItems: 'center',
        justifyContent: 'center',
        paddingHorizontal: 24,
    },
    loadingCard: {
        backgroundColor: colors.cardBackground,
        borderRadius: 14,
        paddingHorizontal: 18,
        paddingVertical: 16,
        alignItems: 'center',
        gap: 10,
        borderWidth: 1,
        borderColor: colors.lightGrayColor,
        minWidth: 180,
    },
    loadingText: Object.assign(Object.assign({}, Fonts.medium14), { color: colors.mainTextColor }),
});
