import { StyleSheet } from 'react-native';
import Fonts from '../../constants/Fonts';
import type { ThemeColors } from '../../constants/Theme';

export const createStyles = (colors: ThemeColors) =>
    StyleSheet.create({
        mainContainer: {
            flex: 1,
            backgroundColor: colors.backgroundColor,
        },
        header: {
            flexDirection: 'row',
            alignItems: 'center',
            justifyContent: 'space-between',
            paddingHorizontal: 20,
            paddingVertical: 16,
            borderBottomWidth: 0.5,
            borderBottomColor: colors.lightGrayColor,
        },
        headerButton: {
            width: 44,
            height: 44,
            borderRadius: 22,
            backgroundColor: colors.btnBackgroundColor,
            alignItems: 'center',
            justifyContent: 'center',
        },
        headerTitle: {
            ...Fonts.medium18,
            color: colors.mainTextColor,
        },
        headerTitleRow: {
            flex: 1,
            alignItems: 'center',
            justifyContent: 'center',
            paddingHorizontal: 12,
        },
        scrollContent: {
            paddingHorizontal: 20,
            paddingTop: 24,
        },
        fieldBlock: {
            marginBottom: 16,
        },
        stepHeaderRow: {
            marginBottom: 18,
            gap: 4,
        },
        stepTopRow: {
            flexDirection: 'row',
            alignItems: 'center',
            justifyContent: 'space-between',
        },
        stepCounter: {
            ...Fonts.regular12,
            color: colors.primaryColor,
        },
        stepTitle: {
            ...Fonts.semibold16,
            color: colors.mainTextColor,
        },
        stepPreviewButton: {
            minWidth: 86,
            borderWidth: 1,
            borderColor: colors.primaryColor,
            borderRadius: 10,
            alignItems: 'center',
            justifyContent: 'center',
            paddingHorizontal: 10,
            paddingVertical: 6,
            backgroundColor: colors.cardBackground,
        },
        stepPreviewButtonDisabled: {
            opacity: 0.45,
        },
        stepPreviewText: {
            ...Fonts.medium13,
            color: colors.primaryColor,
        },
        skipRow: {
            flexDirection: 'row',
            alignItems: 'center',
            gap: 10,
        },
        skipLabel: {
            ...Fonts.regular13,
            color: colors.mainTextColor,
        },
        fieldLabel: {
            ...Fonts.regular12,
            color: colors.grayColor,
            marginBottom: 6,
        },
        fieldInput: {
            borderWidth: 1,
            borderColor: colors.lightGrayColor,
            borderRadius: 12,
            paddingHorizontal: 14,
            paddingVertical: 15,
            minHeight: 54,
            ...Fonts.regular15,
            color: colors.mainTextColor,
            backgroundColor: colors.btnBackgroundColor,
        },
        fieldInputError: {
            borderColor: '#ED5454',
        },
        readonlyField: {
            borderWidth: 1,
            borderColor: colors.lightGrayColor,
            borderRadius: 12,
            paddingHorizontal: 12,
            paddingVertical: 12,
            backgroundColor: colors.btnBackgroundColor,
        },
        readonlyText: {
            ...Fonts.regular14,
            color: colors.mainTextColor,
        },
        dateButton: {
            flexDirection: 'row',
            alignItems: 'center',
            gap: 8,
            borderWidth: 1,
            borderColor: colors.lightGrayColor,
            borderRadius: 12,
            paddingHorizontal: 12,
            paddingVertical: 12,
            backgroundColor: colors.btnBackgroundColor,
        },
        dateText: {
            ...Fonts.regular14,
            color: colors.mainTextColor,
        },
        fieldTextarea: {
            minHeight: 160,
            textAlignVertical: 'top',
        },
        mediaHeader: {
            flexDirection: 'row',
            alignItems: 'center',
            justifyContent: 'space-between',
            marginBottom: 10,
        },
        mediaAddButton: {
            flexDirection: 'row',
            alignItems: 'center',
            gap: 6,
            backgroundColor: colors.primaryColor,
            borderRadius: 10,
            paddingHorizontal: 12,
            paddingVertical: 8,
        },
        mediaAddText: {
            ...Fonts.regular12,
            color: colors.pureWhite,
        },
        mediaGrid: {
            flexDirection: 'row',
            flexWrap: 'wrap',
            gap: 10,
            marginBottom: 16,
        },
        mediaTile: {
            width: 88,
            height: 88,
            borderRadius: 12,
            overflow: 'hidden',
            backgroundColor: colors.btnBackgroundColor,
        },
        mediaImage: {
            width: '100%',
            height: '100%',
        },
        mediaBadge: {
            position: 'absolute',
            bottom: 6,
            right: 6,
            paddingHorizontal: 6,
            paddingVertical: 2,
            borderRadius: 6,
            backgroundColor: 'rgba(0,0,0,0.55)',
        },
        mediaBadgeText: {
            ...Fonts.regular10,
            color: colors.pureWhite,
        },
        mediaEmptyText: {
            ...Fonts.regular12,
            color: colors.grayColor,
        },
        actionRow: {
            flexDirection: 'row',
            alignItems: 'center',
            gap: 12,
            marginTop: 8,
        },
        saveButton: {
            flex: 1,
            backgroundColor: colors.primaryColor,
            borderRadius: 14,
            alignItems: 'center',
            justifyContent: 'center',
            minHeight: 56,
            paddingVertical: 14,
        },
        saveButtonDisabled: {
            opacity: 0.45,
        },
        saveText: {
            ...Fonts.medium14,
            color: colors.pureWhite,
        },
        skipSecondaryButton: {
            marginTop: 10,
            borderWidth: 1,
            borderColor: colors.lightGrayColor,
            borderRadius: 12,
            alignItems: 'center',
            justifyContent: 'center',
            paddingVertical: 12,
            backgroundColor: colors.cardBackground,
        },
        skipSecondaryText: {
            ...Fonts.medium14,
            color: colors.subTextColor,
        },
        deleteButton: {
            marginTop: 16,
            borderRadius: 12,
            backgroundColor: '#FFECEC',
            paddingVertical: 12,
            alignItems: 'center',
            flexDirection: 'row',
            justifyContent: 'center',
            gap: 8,
        },
        deleteText: {
            ...Fonts.medium14,
            color: '#ED5454',
        },
        modalOverlay: {
            position: 'absolute',
            top: 0,
            left: 0,
            right: 0,
            bottom: 0,
            backgroundColor: 'rgba(0,0,0,0.45)',
            justifyContent: 'center',
            paddingHorizontal: 20,
        },
        modalBackdrop: {
            position: 'absolute',
            top: 0,
            bottom: 0,
            left: 0,
            right: 0,
        },
        dateModalContainer: {
            backgroundColor: colors.cardBackground,
            borderRadius: 18,
            padding: 16,
            borderWidth: 1,
            borderColor: colors.lightGrayColor,
        },
        dateModalTitle: {
            ...Fonts.semibold16,
            color: colors.mainTextColor,
        },
        modalDoneButton: {
            marginTop: 12,
            borderRadius: 12,
            backgroundColor: colors.primaryColor,
            paddingVertical: 12,
            alignItems: 'center',
            justifyContent: 'center',
        },
        modalDoneButtonText: {
            ...Fonts.semibold13,
            color: colors.pureWhite,
        },
        eventList: {
            maxHeight: 260,
        },
        eventListContent: {
            marginTop: 10,
            gap: 8,
        },
        eventRow: {
            borderWidth: 1,
            borderColor: colors.lightGrayColor,
            borderRadius: 10,
            paddingHorizontal: 12,
            paddingVertical: 10,
            marginBottom: 8,
            backgroundColor: colors.btnBackgroundColor,
        },
        eventRowActive: {
            borderColor: colors.primaryColor,
            backgroundColor: colors.cardBackground,
        },
        eventRowText: {
            ...Fonts.regular14,
            color: colors.mainTextColor,
        },
        eventRowTextActive: {
            color: colors.primaryColor,
        },
        peopleChipsRow: {
            marginTop: 10,
            flexDirection: 'row',
            flexWrap: 'wrap',
            gap: 8,
        },
        peopleChip: {
            flexDirection: 'row',
            alignItems: 'center',
            gap: 6,
            borderWidth: 1,
            borderColor: colors.lightGrayColor,
            borderRadius: 999,
            paddingHorizontal: 10,
            paddingVertical: 6,
            backgroundColor: colors.btnBackgroundColor,
        },
        peopleChipText: {
            ...Fonts.regular12,
            color: colors.mainTextColor,
        },
        previewCard: {
            borderWidth: 1,
            borderColor: colors.lightGrayColor,
            borderRadius: 14,
            padding: 14,
            backgroundColor: colors.cardBackground,
            gap: 8,
            marginBottom: 8,
        },
        previewTitle: {
            ...Fonts.semibold16,
            color: colors.mainTextColor,
        },
        previewMeta: {
            ...Fonts.regular12,
            color: colors.subTextColor,
        },
        previewText: {
            ...Fonts.regular14,
            color: colors.mainTextColor,
        },
        loadingOverlay: {
            position: 'absolute',
            top: 0,
            left: 0,
            right: 0,
            bottom: 0,
            backgroundColor: 'rgba(0,0,0,0.35)',
            alignItems: 'center',
            justifyContent: 'center',
            paddingHorizontal: 24,
        },
        loadingCard: {
            backgroundColor: colors.cardBackground,
            borderRadius: 14,
            paddingHorizontal: 18,
            paddingVertical: 16,
            alignItems: 'center',
            gap: 10,
            borderWidth: 1,
            borderColor: colors.lightGrayColor,
            minWidth: 180,
        },
        loadingText: {
            ...Fonts.medium14,
            color: colors.mainTextColor,
        },
    });
