import {Dimensions, StyleSheet} from 'react-native';
import Fonts from '../../constants/Fonts';
import type {ThemeColors} from '../../constants/Theme';

const {width} = Dimensions.get('window');
const cardWidth = (width - 40 - 12) / 2;

export const createStyles = (colors: ThemeColors) =>
  StyleSheet.create({
    mainContainer: {
      flex: 1,
      backgroundColor: colors.backgroundColor,
    },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: 20,
      paddingVertical: 16,
      borderBottomWidth: 0.5,
      borderBottomColor: colors.lightGrayColor,
    },
    headerButton: {
      width: 44,
      height: 44,
      borderRadius: 22,
      backgroundColor: colors.btnBackgroundColor,
      alignItems: 'center',
      justifyContent: 'center',
    },
    headerTitle: {
      ...Fonts.medium18,
      color: colors.mainTextColor,
    },
    headerCountBadge: {
      minWidth: 44,
      height: 32,
      borderRadius: 16,
      backgroundColor: colors.btnBackgroundColor,
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: 10,
    },
    headerCountText: {
      ...Fonts.regular12,
      color: colors.grayColor,
    },

    dashboardContent: {
      paddingTop: 20,
      paddingHorizontal: 20,
    },
    dashboardHero: {
      padding: 18,
      borderRadius: 18,
      borderWidth: 1,
      borderColor: colors.lightGrayColor,
      backgroundColor: colors.cardBackground,
      marginBottom: 16,
      gap: 8,
    },
    dashboardEyebrow: {
      ...Fonts.medium12,
      color: colors.primaryColor,
      textTransform: 'uppercase',
      letterSpacing: 1,
    },
    dashboardTitle: {
      ...Fonts.medium18,
      color: colors.mainTextColor,
    },
    dashboardSubtitle: {
      ...Fonts.regular13,
      color: colors.subTextColor,
      lineHeight: 20,
    },
    periodToggleRow: {
      flexDirection: 'row',
      gap: 10,
      marginBottom: 16,
    },
    periodToggle: {
      flex: 1,
      minHeight: 40,
      borderRadius: 999,
      backgroundColor: colors.btnBackgroundColor,
      borderWidth: 1,
      borderColor: colors.lightGrayColor,
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: 10,
    },
    periodToggleActive: {
      backgroundColor: colors.primaryColor,
      borderColor: colors.primaryColor,
    },
    periodToggleText: {
      ...Fonts.medium12,
      color: colors.subTextColor,
    },
    periodToggleTextActive: {
      color: colors.pureWhite,
    },
    kpiGrid: {
      flexDirection: 'row',
      gap: 12,
      marginBottom: 16,
    },
    kpiCard: {
      flex: 1,
      paddingHorizontal: 14,
      paddingVertical: 16,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: colors.lightGrayColor,
      backgroundColor: colors.cardBackground,
      minHeight: 96,
      justifyContent: 'space-between',
    },
    kpiLabel: {
      ...Fonts.regular12,
      color: colors.subTextColor,
    },
    kpiValue: {
      ...Fonts.medium18,
      color: colors.mainTextColor,
      marginTop: 8,
    },
    dashboardQuickLinks: {
      flexDirection: 'row',
      gap: 12,
      marginBottom: 20,
    },
    dashboardQuickLink: {
      flex: 1,
      paddingHorizontal: 14,
      paddingVertical: 14,
      borderRadius: 16,
      backgroundColor: colors.cardBackground,
      borderWidth: 1,
      borderColor: colors.lightGrayColor,
      minHeight: 88,
      justifyContent: 'space-between',
    },
    dashboardQuickLinkTitle: {
      ...Fonts.medium14,
      color: colors.mainTextColor,
    },
    dashboardQuickLinkSubtitle: {
      ...Fonts.regular12,
      color: colors.subTextColor,
      lineHeight: 18,
      marginTop: 8,
    },
    dashboardCompetitionCard: {
      borderRadius: 18,
      borderWidth: 1,
      borderColor: colors.lightGrayColor,
      backgroundColor: colors.cardBackground,
      padding: 16,
      marginBottom: 14,
      gap: 14,
    },
    dashboardCompetitionTopRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
    },
    dashboardCompetitionThumb: {
      width: 72,
      height: 72,
      borderRadius: 14,
      backgroundColor: colors.btnBackgroundColor,
    },
    dashboardCompetitionThumbPlaceholder: {
      width: 72,
      height: 72,
      borderRadius: 14,
      backgroundColor: colors.btnBackgroundColor,
    },
    dashboardCompetitionInfo: {
      flex: 1,
      gap: 4,
    },
    dashboardCompetitionTitle: {
      ...Fonts.medium16,
      color: colors.mainTextColor,
    },
    dashboardCompetitionMeta: {
      ...Fonts.regular12,
      color: colors.subTextColor,
      lineHeight: 18,
    },
    trendRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      marginTop: 4,
    },
    trendText: {
      ...Fonts.regular12,
    },
    trendFlatDot: {
      width: 8,
      height: 8,
      borderRadius: 4,
      backgroundColor: colors.subTextColor,
    },
    dashboardCompetitionStatsRow: {
      flexDirection: 'row',
      gap: 10,
    },
    dashboardMiniStat: {
      flex: 1,
      paddingHorizontal: 10,
      paddingVertical: 10,
      borderRadius: 12,
      backgroundColor: colors.btnBackgroundColor,
    },
    dashboardMiniStatLabel: {
      ...Fonts.regular11,
      color: colors.subTextColor,
      marginBottom: 6,
    },
    dashboardMiniStatValue: {
      ...Fonts.medium14,
      color: colors.mainTextColor,
    },
    dashboardCompetitionFooter: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 12,
    },
    dashboardCompetitionFootnote: {
      ...Fonts.regular12,
      color: colors.subTextColor,
    },
    dashboardOpenButton: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      paddingHorizontal: 14,
      paddingVertical: 10,
      borderRadius: 999,
      borderWidth: 1,
      borderColor: colors.primaryColor,
      backgroundColor: colors.secondaryBlueColor,
    },
    dashboardOpenButtonText: {
      ...Fonts.medium12,
      color: colors.primaryColor,
    },

    listContent: {
      paddingTop: 24,
      paddingBottom: 24,
    },
    sectionTitle: {
      ...Fonts.medium18,
      color: colors.mainTextColor,
      marginBottom: 12,
    },
    listHeader: {
      paddingHorizontal: 20,
      marginBottom: 16,
    },
    searchBar: {
      marginTop: 10,
      borderWidth: 1,
      borderColor: colors.lightGrayColor,
      borderRadius: 14,
      paddingHorizontal: 12,
      paddingVertical: 10,
      backgroundColor: colors.btnBackgroundColor,
    },
    searchInput: {
      ...Fonts.regular14,
      color: colors.mainTextColor,
    },
    gridRow: {
      paddingHorizontal: 20,
      gap: 12,
      marginBottom: 12,
    },
    card: {
      width: cardWidth,
      backgroundColor: colors.cardBackground,
      borderRadius: 12,
      borderWidth: 0.5,
      borderColor: colors.lightGrayColor,
      padding: 12,
    },
    cardImage: {
      width: '100%',
      height: 110,
      borderRadius: 8,
    },
    cardMetaRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginTop: 10,
      gap: 10,
    },
    cardMetaText: {
      ...Fonts.regular12,
      color: colors.grayColor,
      flex: 1,
    },
    emptyText: {
      ...Fonts.regular14,
      color: colors.grayColor,
      textAlign: 'center',
      paddingHorizontal: 20,
      marginTop: 16,
    },
    errorText: {
      ...Fonts.regular14,
      color: '#FF3B30',
      textAlign: 'center',
      paddingHorizontal: 20,
      marginTop: 6,
      marginBottom: 16,
    },
    profitCard: {
      marginHorizontal: 20,
      marginBottom: 12,
      padding: 14,
      borderRadius: 12,
      borderWidth: 0.5,
      borderColor: colors.lightGrayColor,
      backgroundColor: colors.cardBackground,
    },
    profitTopRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
    },
    profitThumb: {
      width: 64,
      height: 64,
      borderRadius: 10,
    },
    profitThumbPlaceholder: {
      width: 64,
      height: 64,
      borderRadius: 10,
      backgroundColor: colors.btnBackgroundColor,
    },
    profitInfo: {
      flex: 1,
    },
    profitTitle: {
      ...Fonts.medium14,
      color: colors.mainTextColor,
      marginBottom: 8,
    },
    profitRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 10,
    },
    profitMeta: {
      ...Fonts.regular12,
      color: colors.grayColor,
      flex: 1,
    },
    profitAmount: {
      ...Fonts.medium14,
      color: colors.primaryColor,
    },
    competitionRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 12,
      marginHorizontal: 20,
      marginBottom: 12,
      padding: 14,
      borderRadius: 12,
      borderWidth: 0.5,
      borderColor: colors.lightGrayColor,
      backgroundColor: colors.cardBackground,
    },
    competitionRowInfo: {
      flex: 1,
      gap: 4,
    },
    competitionRowTitle: {
      ...Fonts.medium14,
      color: colors.mainTextColor,
    },
    competitionRowMeta: {
      ...Fonts.regular12,
      color: colors.subTextColor,
    },
    competitionRowMetaSecondary: {
      ...Fonts.regular12,
      color: colors.grayColor,
    },
    competitionBadge: {
      paddingHorizontal: 10,
      paddingVertical: 6,
      borderRadius: 12,
      backgroundColor: colors.btnBackgroundColor,
      borderWidth: 1,
      borderColor: colors.lightGrayColor,
    },
    competitionBadgeText: {
      ...Fonts.medium12,
      color: colors.primaryColor,
    },
    mediaRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      marginHorizontal: 20,
      marginBottom: 12,
      padding: 12,
      borderRadius: 12,
      borderWidth: 0.5,
      borderColor: colors.lightGrayColor,
      backgroundColor: colors.cardBackground,
    },
    mediaThumb: {
      width: 64,
      height: 64,
      borderRadius: 10,
    },
    mediaThumbPlaceholder: {
      width: 64,
      height: 64,
      borderRadius: 10,
      backgroundColor: colors.btnBackgroundColor,
    },
    mediaInfo: {
      flex: 1,
      gap: 4,
    },
    mediaTitle: {
      ...Fonts.medium14,
      color: colors.mainTextColor,
    },
    mediaMeta: {
      ...Fonts.regular12,
      color: colors.grayColor,
    },
    tutorialCard: {
      marginHorizontal: 20,
      marginBottom: 14,
      borderRadius: 14,
      borderWidth: 1,
      borderColor: colors.lightGrayColor,
      backgroundColor: colors.cardBackground,
      padding: 14,
      gap: 10,
    },
    tutorialTitle: {
      ...Fonts.medium16,
      color: colors.mainTextColor,
    },
    tutorialBody: {
      ...Fonts.regular13,
      color: colors.subTextColor,
      lineHeight: 18,
    },
    tutorialImage: {
      width: '100%',
      height: 140,
      borderRadius: 10,
      backgroundColor: colors.btnBackgroundColor,
    },
    tutorialPrimaryButton: {
      minHeight: 46,
      borderRadius: 12,
      backgroundColor: colors.primaryColor,
      alignItems: 'center',
      justifyContent: 'center',
    },
    tutorialPrimaryButtonText: {
      ...Fonts.medium14,
      color: colors.pureWhite,
    },
    loadingOverlay: {
      position: 'absolute',
      left: 0,
      right: 0,
      top: 0,
      bottom: 0,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: 'rgba(0,0,0,0.02)',
    },
  });
