const Images = {
    logo: require('../assets/imgs/logo.png'),
    englishFlag: require('../assets/imgs/english-flag.png'),
    dutchFlag: require('../assets/imgs/dutch-flag.png'),
    signup2: require('../assets/imgs/signup2.png'),
    signup3: require('../assets/imgs/signup3.png'),
    signup4: require('../assets/imgs/signup4.png'),
    trackAndField: require('../assets/imgs/track-and-field.png'),
    roadEvents: require('../assets/imgs/road-events.png'),
    boxing: require('../assets/imgs/boxing.png'),
    signupLock: require('../assets/imgs/signup-lock.png'),
    loginImg: require('../assets/imgs/login.png'),
    registerImg: require('../assets/imgs/register.png'),
    talentImg: require('../assets/imgs/talent.png'),
    profilePic: require('../assets/imgs/user.png'),
    event1: require('../assets/imgs/event1.png'),
    congratulations: require('../assets/imgs/congratulations.png'),
    profile1: require('../assets/imgs/profile.png'),
    map: require('../assets/imgs/map.png'),
    photo1: require('../assets/imgs/foto1.png'),
    // photo2: require('../assets/imgs/foto2.png'),
    photo3: require('../assets/imgs/foto3.png'),
    photo4: require('../assets/imgs/foto4.png'),
    photo5: require('../assets/imgs/foto5.png'),
    photo6: require('../assets/imgs/foto6.png'),
    photo7: require('../assets/imgs/foto7.png'),
    photo8: require('../assets/imgs/foto8.png'),
    photo9: require('../assets/imgs/foto9.png'),
    fiverr: require('../assets/imgs/fiverr.png'),
    noResult: require('../assets/imgs/no-result.png'),
    advertisement: require('../assets/imgs/advertisement.png'),
    fileUpload: require('../assets/imgs/fileUpload.png'),
}

export default Images;  