import { StyleSheet } from 'react-native';
import { lightColors } from '../../constants/Theme';
import Fonts from '../../constants/Fonts';
export const createStyles = (colors) => StyleSheet.create({
    mainContainer: {
        flex: 1,
        backgroundColor: colors.whiteColor,
    },
    header: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 20,
        paddingVertical: 16,
        borderBottomWidth: 0.5,
        borderBottomColor: colors.lightGrayColor,
    },
    headerButton: {
        width: 44,
        height: 44,
        borderRadius: 22,
        backgroundColor: colors.cardBackground,
        borderWidth: 1,
        borderColor: colors.lightGrayColor,
        alignItems: 'center',
        justifyContent: 'center',
    },
    headerTitle: Object.assign(Object.assign({}, Fonts.medium18), { color: colors.mainTextColor }),
    headerSwitchButton: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
        paddingHorizontal: 14,
        paddingVertical: 9,
        borderRadius: 999,
        backgroundColor: colors.secondaryBlueColor,
        borderWidth: 1,
        borderColor: colors.primaryColor,
    },
    headerSwitchText: Object.assign(Object.assign({}, Fonts.regular14), { color: colors.primaryColor }),
    scrollContent: {
        paddingHorizontal: 20,
        paddingTop: 24,
    },
    titleRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    renameRow: {
        marginTop: 12,
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
    },
    renameInput: Object.assign({ flex: 1, borderWidth: 1, borderColor: colors.lightGrayColor, borderRadius: 10, minHeight: 42, paddingHorizontal: 12, color: colors.mainTextColor, backgroundColor: colors.btnBackgroundColor }, Fonts.regular14),
    renameSaveButton: {
        minHeight: 42,
        paddingHorizontal: 14,
        borderRadius: 10,
        backgroundColor: colors.primaryColor,
        alignItems: 'center',
        justifyContent: 'center',
    },
    renameSaveButtonDisabled: {
        opacity: 0.65,
    },
    renameSaveText: Object.assign(Object.assign({}, Fonts.medium13), { color: colors.pureWhite }),
    title: Object.assign(Object.assign({}, Fonts.medium18), { color: colors.mainTextColor, flex: 1 }),
    selectTopButton: {
        backgroundColor: colors.secondaryBlueColor,
        borderColor: colors.primaryColor,
        borderWidth: 1,
        paddingHorizontal: 12,
        paddingVertical: 7,
        borderRadius: 999,
        minHeight: 34,
        alignItems: 'center',
        justifyContent: 'center',
    },
    selectTopButtonText: Object.assign(Object.assign({}, Fonts.regular12), { color: colors.primaryColor }),
    cancelButton: {
        backgroundColor: 'rgba(237, 84, 84, 0.12)',
        borderWidth: 1,
        borderColor: '#ED5454',
        paddingHorizontal: 14,
        paddingVertical: 9,
        borderRadius: 999,
        minHeight: 38,
        alignItems: 'center',
        justifyContent: 'center',
    },
    cancelButtonText: Object.assign(Object.assign({}, Fonts.regular14), { color: '#FF0000' }),
    addButton: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: colors.primaryColor,
        height: 46,
        borderRadius: 12,
        borderWidth: 1,
        borderColor: 'rgba(255,255,255,0.14)',
        gap: 6,
    },
    addButtonText: Object.assign(Object.assign({}, Fonts.medium14), { color: colors.pureWhite }),
    deleteButton: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: 'rgba(237, 84, 84, 0.12)',
        borderWidth: 1,
        borderColor: '#ED5454',
        height: 46,
        borderRadius: 12,
        gap: 6,
    },
    actionRow: {
        flexDirection: 'row',
        gap: 10,
    },
    deleteButtonText: Object.assign(Object.assign({}, Fonts.medium14), { color: '#FF0000' }),
    photosContainer: {
        borderWidth: 1,
        borderColor: colors.lightGrayColor,
        borderRadius: 18,
        padding: 12,
        backgroundColor: colors.cardBackground,
    },
    photosGrid: {
        width: '100%',
        flexDirection: 'row',
        flexWrap: 'wrap',
        justifyContent: 'flex-start',
        alignContent: 'flex-start',
        columnGap: 10,
        rowGap: 10,
        gap: 10,
    },
    photoImage: {
        height: 124,
        borderRadius: 10,
    },
    photoImageContainer: {
        height: 126,
        borderRadius: 12,
        borderWidth: 1,
        borderColor: 'transparent',
        overflow: 'hidden',
    },
    photoImageContainerSelected: {
        borderColor: colors.primaryColor,
        borderWidth: 2,
    },
    photoImageContainerSelectedDelete: {
        borderColor: '#ED5454',
        borderWidth: 2,
    },
    selectionBadge: {
        position: 'absolute',
        top: 4,
        right: 4,
        width: 22,
        height: 22,
        borderRadius: 11,
        backgroundColor: colors.primaryColor,
        borderWidth: 1,
        borderColor: colors.pureWhite,
        alignItems: 'center',
        justifyContent: 'center',
    },
    selectionBadgeDelete: {
        backgroundColor: '#FF0000',
    },
    selectionBadgeText: {
        fontSize: 11,
        color: colors.pureWhite,
        fontWeight: '600',
    },
    confirmDeleteButton: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#ED5454',
        height: 42,
        borderRadius: 12,
        gap: 6,
    },
    confirmDeleteButtonText: Object.assign(Object.assign({}, Fonts.medium14), { color: colors.pureWhite }),
    confirmTopButton: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: colors.primaryColor,
        height: 42,
        borderRadius: 12,
        gap: 6,
    },
    confirmTopButtonText: Object.assign(Object.assign({}, Fonts.medium14), { color: colors.pureWhite }),
});
const Styles = createStyles(lightColors);
export default Styles;
