import { StyleSheet } from 'react-native';
import Fonts from '../../constants/Fonts';
import { lightColors } from '../../constants/Theme';
export const createStyles = (colors) => StyleSheet.create({
    mainContainer: {
        flex: 1,
        backgroundColor: colors.backgroundColor,
    },
    header: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 20,
        paddingVertical: 14,
        borderBottomWidth: 0.5,
        borderBottomColor: colors.borderColor,
        gap: 12,
    },
    backButton: {
        width: 44,
        height: 44,
        borderRadius: 22,
        backgroundColor: colors.btnBackgroundColor,
        alignItems: 'center',
        justifyContent: 'center',
    },
    headerCenter: {
        flex: 1,
        minWidth: 0,
        gap: 2,
    },
    headerRight: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 10,
    },
    headerAction: {
        width: 44,
        height: 44,
        alignItems: 'center',
        justifyContent: 'center',
        borderRadius: 22,
        backgroundColor: colors.btnBackgroundColor,
    },
    headerActionDark: {
        backgroundColor: 'rgba(255,255,255,0.10)',
        borderWidth: 1,
        borderColor: 'rgba(255,255,255,0.16)',
    },
    headerActionLight: {
        backgroundColor: '#E5E7EB',
        borderWidth: 1,
        borderColor: '#D1D5DB',
    },
    headerTitle: Object.assign(Object.assign({}, Fonts.medium14), { color: colors.mainTextColor }),
    headerSubtitle: Object.assign(Object.assign({}, Fonts.regular12), { color: colors.subTextColor }),
    headerMetricPill: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
        paddingHorizontal: 12,
        height: 36,
        borderRadius: 18,
        backgroundColor: colors.btnBackgroundColor,
    },
    headerMetricPillLight: {
        backgroundColor: '#F3F4F6',
        borderWidth: 1,
        borderColor: '#D1D5DB',
    },
    headerMetricText: Object.assign(Object.assign({}, Fonts.medium12), { color: colors.mainTextColor }),
    content: {
        flex: 1,
        paddingHorizontal: 0,
        paddingTop: 0,
    },
    contentFull: {
        paddingHorizontal: 0,
        paddingTop: 0,
    },
    contentInset: {
        paddingHorizontal: 20,
        paddingTop: 16,
        paddingBottom: 18,
    },
    mediaStage: {
        width: '100%',
        flex: 1,
        minHeight: 0,
        justifyContent: 'center',
    },
    questionCard: {
        backgroundColor: colors.cardBackground,
        borderRadius: 16,
        borderWidth: 1,
        borderColor: colors.borderColor,
        paddingHorizontal: 18,
        paddingVertical: 16,
        alignItems: 'center',
        justifyContent: 'center',
        shadowColor: '#000',
        shadowOpacity: 0.08,
        shadowRadius: 10,
        shadowOffset: { width: 0, height: 6 },
        elevation: 3,
    },
    questionText: Object.assign(Object.assign({}, Fonts.semibold14), { color: colors.mainTextColor, textAlign: 'center', marginBottom: 10 }),
    buttonsRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 12,
    },
    noButton: {
        backgroundColor: '#FCECEC',
        borderRadius: 999,
        paddingHorizontal: 16,
        paddingVertical: 10,
        minWidth: 120,
        height: 36,
        alignItems: 'center',
        justifyContent: 'center',
        borderWidth: 1,
        borderColor: '#F5A1A1',
    },
    yesButton: {
        backgroundColor: colors.primaryColor,
        borderRadius: 999,
        paddingHorizontal: 16,
        paddingVertical: 10,
        minWidth: 120,
        height: 36,
        alignItems: 'center',
        justifyContent: 'center',
    },
    buttonText: Object.assign(Object.assign({}, Fonts.semibold12), { color: colors.pureWhite }),
    noButtonText: Object.assign(Object.assign({}, Fonts.semibold12), { color: '#D64545' }),
    photoContainer: {
        flex: 1,
        borderRadius: 10,
        overflow: 'hidden',
        marginBottom: 20,
        position: 'relative',
        backgroundColor: colors.backgroundColor,
        alignItems: 'stretch',
        justifyContent: 'flex-start',
    },
    photoContainerFull: {
        borderRadius: 0,
        marginBottom: 0,
    },
    photoContainerFullBleed: {
        borderRadius: 0,
        marginBottom: 0,
    },
    photoImage: {
        width: '100%',
        height: '100%',
        backgroundColor: 'transparent',
    },
    zoomablePhoto: {
        backgroundColor: 'transparent',
        alignSelf: 'center',
    },
    photoZoomScroll: {
        flex: 1,
        width: '100%',
    },
    photoZoomContent: {
        flexGrow: 1,
        alignItems: 'stretch',
        justifyContent: 'flex-start',
    },
    videoSkeleton: Object.assign(Object.assign({}, StyleSheet.absoluteFillObject), { backgroundColor: colors.cardBackground, zIndex: 2 }),
    videoControlsOverlay: {
        position: 'absolute',
        left: 0,
        right: 0,
        bottom: 0,
        paddingHorizontal: 16,
        paddingBottom: 16,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        flexWrap: 'wrap',
    },
    downloadOverlay: Object.assign(Object.assign({}, StyleSheet.absoluteFillObject), { backgroundColor: 'rgba(0,0,0,0.35)', justifyContent: 'center', alignItems: 'center', zIndex: 20 }),
    downloadCard: {
        width: '78%',
        backgroundColor: colors.pureWhite,
        borderRadius: 18,
        paddingHorizontal: 20,
        paddingVertical: 18,
        alignItems: 'center',
        gap: 12,
    },
    downloadTitle: Object.assign(Object.assign({}, Fonts.semibold16), { color: colors.mainTextColor }),
    downloadProgressTrack: {
        width: '100%',
        height: 8,
        borderRadius: 8,
        backgroundColor: '#E5E7EB',
        overflow: 'hidden',
    },
    downloadProgressFill: {
        height: '100%',
        backgroundColor: colors.primaryColor,
        borderRadius: 8,
    },
    downloadProgressLabel: Object.assign(Object.assign({}, Fonts.regular12), { color: colors.subTextColor }),
    videoTimeRow: {
        paddingHorizontal: 10,
        paddingVertical: 4,
        borderRadius: 10,
        backgroundColor: 'rgba(0,0,0,0.45)',
        marginBottom: 8,
    },
    videoTapOverlay: Object.assign(Object.assign({}, StyleSheet.absoluteFillObject), { alignItems: 'center', justifyContent: 'center', paddingHorizontal: 16, paddingVertical: 12 }),
    videoTimeText: Object.assign(Object.assign({}, Fonts.regular12), { color: colors.pureWhite }),
    videoScrubber: {
        width: '100%',
        height: 24,
    },
    videoScrubberWrap: {
        width: '100%',
    },
    videoPlayBadge: {
        width: 72,
        height: 72,
        borderRadius: 36,
        backgroundColor: 'rgba(0,0,0,0.25)',
        alignItems: 'center',
        justifyContent: 'center',
    },
    videoErrorText: Object.assign(Object.assign({}, Fonts.regular12), { color: colors.pureWhite, textAlign: 'center', marginTop: 10, paddingHorizontal: 10, paddingVertical: 6, borderRadius: 10, backgroundColor: 'rgba(0,0,0,0.55)' }),
    videoPlaceholder: {
        width: '100%',
        height: '100%',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: colors.cardBackground,
    },
    videoPlaceholderText: Object.assign(Object.assign({}, Fonts.regular14), { color: colors.subTextColor }),
    topRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginTop: 0,
        marginBottom: 10,
        marginHorizontal: 4,
    },
    viewsContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 4,
    },
    viewsText: Object.assign(Object.assign({}, Fonts.regular16), { color: colors.mainTextColor }),
    buyButton: {
        backgroundColor: colors.primaryColor,
        borderRadius: 8,
        paddingHorizontal: 16,
        paddingVertical: 10,
        width: 97,
        height: 38,
        alignItems: 'center',
        justifyContent: 'center',
    },
    buyButtonText: Object.assign(Object.assign({}, Fonts.regular14), { color: colors.pureWhite }),
    moreMenuOverlay: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        paddingHorizontal: 20,
    },
    moreMenuBackdrop: {
        position: 'absolute',
        top: 0,
        bottom: 0,
        left: 0,
        right: 0,
        backgroundColor: 'rgba(0,0,0,0.45)',
    },
    moreMenuContainer: {
        width: '100%',
        maxWidth: 420,
        backgroundColor: colors.modalBackground,
        borderRadius: 16,
        borderWidth: 0.5,
        borderColor: colors.lightGrayColor,
        padding: 14,
    },
    moreMenuTitle: Object.assign(Object.assign({}, Fonts.medium16), { color: colors.mainTextColor, marginBottom: 8 }),
    moreMenuDivider: {
        height: 1,
        backgroundColor: colors.lightGrayColor,
        marginBottom: 8,
    },
    moreMenuAction: {
        backgroundColor: colors.secondaryColor,
        borderRadius: 10,
        paddingHorizontal: 12,
        paddingVertical: 12,
        marginBottom: 8,
    },
    moreMenuActionText: Object.assign(Object.assign({}, Fonts.regular14), { color: colors.mainTextColor }),
    moreMenuCancel: {
        marginTop: 4,
        borderWidth: 1,
        borderColor: colors.lightGrayColor,
        borderRadius: 10,
        paddingHorizontal: 12,
        paddingVertical: 12,
        alignItems: 'center',
        backgroundColor: colors.btnBackgroundColor,
    },
    moreMenuCancelText: Object.assign(Object.assign({}, Fonts.medium14), { color: colors.grayColor }),
    infoModalContainer: {
        width: '100%',
        maxWidth: 420,
        backgroundColor: colors.modalBackground,
        borderRadius: 16,
        borderWidth: 0.5,
        borderColor: colors.lightGrayColor,
        padding: 16,
        gap: 10,
    },
    infoModalTitle: Object.assign(Object.assign({}, Fonts.medium16), { color: colors.mainTextColor }),
    infoModalText: Object.assign(Object.assign({}, Fonts.regular14), { color: colors.subTextColor }),
    infoModalSubmitButton: {
        alignSelf: 'stretch',
        alignItems: 'center',
        backgroundColor: colors.primaryColor,
        borderRadius: 10,
        paddingHorizontal: 16,
        paddingVertical: 12,
    },
    infoModalSubmitButtonText: Object.assign(Object.assign({}, Fonts.medium14), { color: colors.pureWhite }),
});
// Backward compatibility
const Styles = createStyles(lightColors);
export default Styles;
