import { StyleSheet } from 'react-native';
import Fonts from '../../constants/Fonts';
import { ThemeColors, lightColors } from '../../constants/Theme';

export const createStyles = (colors: ThemeColors) => StyleSheet.create({
    mainContainer: {
        flex: 1,
        backgroundColor: colors.backgroundColor,
    },
    header: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 20,
        paddingVertical: 16,
        borderBottomWidth: 0.5,
        borderBottomColor: colors.borderColor,
    },
    backButton: {
        width: 44,
        height: 44,
        borderRadius: 22,
        backgroundColor: colors.btnBackgroundColor,
        alignItems: 'center',
        justifyContent: 'center',
    },
    headerAction: {
        width: 44,
        height: 44,
        alignItems: 'center',
        justifyContent: 'center',
    },
    headerTitle: {
        ...Fonts.medium14,
        color: colors.mainTextColor,
    },
    content: {
        flex: 1,
        paddingHorizontal: 20,
        paddingTop: 16,
    },
    contentFull: {
        paddingHorizontal: 0,
        paddingTop: 0,
    },
    questionCard: {
        backgroundColor: colors.cardBackground,
        borderRadius: 16,
        borderWidth: 1,
        borderColor: colors.borderColor,
        paddingHorizontal: 18,
        paddingVertical: 16,
        alignItems: 'center',
        justifyContent: 'center',
        shadowColor: '#000',
        shadowOpacity: 0.08,
        shadowRadius: 10,
        shadowOffset: {width: 0, height: 6},
        elevation: 3,
    },
    questionText: {
        ...Fonts.semibold14,
        color: colors.mainTextColor,
        textAlign: 'center',
        marginBottom: 10,
    },
    buttonsRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 12,
    },
    noButton: {
        backgroundColor: '#FCECEC',
        borderRadius: 999,
        paddingHorizontal: 16,
        paddingVertical: 10,
        minWidth: 120,
        height: 36,
        alignItems: 'center',
        justifyContent: 'center',
        borderWidth: 1,
        borderColor: '#F5A1A1',
    },
    yesButton: {
        backgroundColor: colors.primaryColor,
        borderRadius: 999,
        paddingHorizontal: 16,
        paddingVertical: 10,
        minWidth: 120,
        height: 36,
        alignItems: 'center',
        justifyContent: 'center',
    },
    buttonText: {
        ...Fonts.semibold12,
        color: colors.pureWhite,
    },
    noButtonText: {
        ...Fonts.semibold12,
        color: '#D64545',
    },
    photoContainer: {
        flex: 1,
        borderRadius: 10,
        overflow: 'hidden',
        marginBottom: 20,
        position: 'relative',
    },
    photoContainerFull: {
        borderRadius: 0,
        marginBottom: 0,
    },
    photoImage: {
        width: '100%',
        height: '100%',
    },
    videoSkeleton: {
        ...StyleSheet.absoluteFillObject,
        backgroundColor: colors.cardBackground,
        zIndex: 2,
    },
    videoControlsOverlay: {
        position: 'absolute',
        left: 0,
        right: 0,
        bottom: 0,
        paddingHorizontal: 16,
        paddingBottom: 16,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        flexWrap: 'wrap',
    },
    downloadOverlay: {
        ...StyleSheet.absoluteFillObject,
        backgroundColor: 'rgba(0,0,0,0.35)',
        justifyContent: 'center',
        alignItems: 'center',
        zIndex: 20,
    },
    downloadCard: {
        width: '78%',
        backgroundColor: colors.pureWhite,
        borderRadius: 18,
        paddingHorizontal: 20,
        paddingVertical: 18,
        alignItems: 'center',
        gap: 12,
    },
    downloadTitle: {
        ...Fonts.semibold16,
        color: colors.mainTextColor,
    },
    downloadProgressTrack: {
        width: '100%',
        height: 8,
        borderRadius: 8,
        backgroundColor: '#E5E7EB',
        overflow: 'hidden',
    },
    downloadProgressFill: {
        height: '100%',
        backgroundColor: colors.primaryColor,
        borderRadius: 8,
    },
    downloadProgressLabel: {
        ...Fonts.regular12,
        color: colors.textSecondary,
    },
    videoTimeRow: {
        paddingHorizontal: 10,
        paddingVertical: 4,
        borderRadius: 10,
        backgroundColor: 'rgba(0,0,0,0.45)',
        marginBottom: 8,
    },
    videoTapOverlay: {
        ...StyleSheet.absoluteFillObject,
        alignItems: 'center',
        justifyContent: 'center',
        paddingHorizontal: 16,
        paddingVertical: 12,
    },
    videoTimeText: {
        ...Fonts.regular12,
        color: colors.pureWhite,
    },
    videoScrubber: {
        width: '100%',
        height: 24,
    },
    videoScrubberWrap: {
        width: '100%',
    },
    videoPlayBadge: {
        width: 72,
        height: 72,
        borderRadius: 36,
        backgroundColor: 'rgba(0,0,0,0.25)',
        alignItems: 'center',
        justifyContent: 'center',
    },
    videoErrorText: {
        ...Fonts.regular12,
        color: colors.pureWhite,
        textAlign: 'center',
        marginTop: 10,
        paddingHorizontal: 10,
        paddingVertical: 6,
        borderRadius: 10,
        backgroundColor: 'rgba(0,0,0,0.55)',
    },
    videoPlaceholder: {
        width: '100%',
        height: '100%',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: colors.cardBackground,
    },
    videoPlaceholderText: {
        ...Fonts.regular14,
        color: colors.subTextColor,
    },
    topRow: {
        position: 'absolute',
        top: 12,
        left: 14,
        right: 14,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    viewsContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 4,
    },
    viewsText: {
        ...Fonts.regular16,
        color: colors.pureWhite,
    },
    buyButton: {
        backgroundColor: colors.primaryColor,
        borderRadius: 8,
        paddingHorizontal: 16,
        paddingVertical: 10,
        width: 97,
        height: 38,
        alignItems: 'center',
        justifyContent: 'center',
    },
    buyButtonText: {
        ...Fonts.regular14,
        color: colors.pureWhite,
    },
    moreMenuOverlay: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        paddingHorizontal: 20,
    },
    moreMenuBackdrop: {
        position: 'absolute',
        top: 0,
        bottom: 0,
        left: 0,
        right: 0,
        backgroundColor: 'rgba(0,0,0,0.45)',
    },
    moreMenuContainer: {
        width: '100%',
        maxWidth: 420,
        backgroundColor: colors.modalBackground,
        borderRadius: 16,
        borderWidth: 0.5,
        borderColor: colors.lightGrayColor,
        padding: 14,
    },
    moreMenuAction: {
        backgroundColor: colors.secondaryColor,
        borderRadius: 10,
        paddingHorizontal: 12,
        paddingVertical: 12,
        marginBottom: 8,
    },
    moreMenuActionText: {
        ...Fonts.regular14,
        color: colors.mainTextColor,
    },
    moreMenuCancel: {
        marginTop: 4,
        borderWidth: 1,
        borderColor: colors.lightGrayColor,
        borderRadius: 10,
        paddingHorizontal: 12,
        paddingVertical: 12,
        alignItems: 'center',
        backgroundColor: colors.btnBackgroundColor,
    },
    moreMenuCancelText: {
        ...Fonts.medium14,
        color: colors.grayColor,
    },
});

// Backward compatibility
const Styles = createStyles(lightColors);
export default Styles;
