import { StyleSheet } from 'react-native';
import Fonts from '../../../constants/Fonts';
import { ThemeColors, lightColors } from '../../../constants/Theme';

export const createStyles = (colors: ThemeColors) => StyleSheet.create({
    mainContainer: {
        flex: 1,
        backgroundColor: colors.backgroundColor,
    },
    header: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 20,
        paddingVertical: 10,
        borderBottomWidth: 0.5,
        borderBottomColor: colors.lightGrayColor,
    },
    headerButton: {
        width: 44,
        height: 44,
        borderRadius: 22,
        backgroundColor: colors.btnBackgroundColor,
        alignItems: 'center',
        justifyContent: 'center',
    },
    headerTitle: {
        ...Fonts.medium18,
        color: colors.mainTextColor,
    },
    container: {
        flex: 1,
        paddingHorizontal: 20,
    },
    scrollContent: {
        paddingVertical: 24,
        paddingBottom: 36,
    },
    infoCard: {
        backgroundColor: 'rgba(60, 130, 246, 0.08)',
        borderWidth: 0.5,
        borderColor: colors.primaryColor,
        borderRadius: 12,
        padding: 16,
    },
    infoHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 12,
        marginBottom: 8,
    },
    infoIconContainer: {
        width: 48,
        height: 48,
        borderRadius: 12,
        backgroundColor: colors.secondaryColor,
        alignItems: 'center',
        justifyContent: 'center',
    },
    infoTitle: {
        ...Fonts.medium18,
        color: colors.mainTextColor,
        flex: 1,
    },
    infoDescription: {
        ...Fonts.regular14,
        color: colors.grayColor,
        lineHeight: 21,
    },
    loadingCard: {
        minHeight: 88,
        borderRadius: 12,
        borderWidth: 0.5,
        borderColor: colors.lightGrayColor,
        backgroundColor: colors.cardBackground,
        alignItems: 'center',
        justifyContent: 'center',
        gap: 10,
        marginBottom: 16,
    },
    loadingText: {
        ...Fonts.regular14,
        color: colors.grayColor,
    },
    errorCard: {
        borderRadius: 12,
        borderWidth: 0.5,
        borderColor: '#ED5454',
        backgroundColor: 'rgba(237, 84, 84, 0.08)',
        padding: 14,
        marginBottom: 16,
    },
    errorTitle: {
        ...Fonts.medium14,
        color: '#ED5454',
        marginBottom: 4,
    },
    errorText: {
        ...Fonts.regular13,
        color: colors.mainTextColor,
        lineHeight: 19,
    },
    statsGrid: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 12,
        marginBottom: 16,
    },
    statCard: {
        width: '47%',
        borderRadius: 12,
        borderWidth: 0.5,
        borderColor: colors.lightGrayColor,
        backgroundColor: colors.cardBackground,
        padding: 14,
        gap: 4,
    },
    statValue: {
        ...Fonts.medium20,
        color: colors.mainTextColor,
    },
    statLabel: {
        ...Fonts.regular12,
        color: colors.grayColor,
    },
    sectionCard: {
        borderRadius: 12,
        borderWidth: 0.5,
        borderColor: colors.lightGrayColor,
        backgroundColor: colors.cardBackground,
        padding: 16,
        marginBottom: 12,
    },
    sectionHeaderRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginBottom: 6,
        gap: 12,
    },
    sectionTitle: {
        ...Fonts.medium16,
        color: colors.mainTextColor,
        flex: 1,
    },
    sectionCount: {
        ...Fonts.medium16,
        color: colors.primaryColor,
    },
    sectionDescription: {
        ...Fonts.regular13,
        color: colors.grayColor,
        lineHeight: 19,
    },
    warningCard: {
        borderRadius: 12,
        borderWidth: 0.5,
        borderColor: colors.primaryColor,
        backgroundColor: 'rgba(60, 130, 246, 0.08)',
        padding: 14,
        marginTop: 4,
        marginBottom: 16,
    },
    warningText: {
        ...Fonts.regular13,
        color: colors.mainTextColor,
        lineHeight: 19,
    },
    secondaryButton: {
        height: 54,
        borderRadius: 12,
        borderWidth: 0.5,
        borderColor: colors.lightGrayColor,
        backgroundColor: colors.cardBackground,
        alignItems: 'center',
        justifyContent: 'center',
    },
    secondaryButtonText: {
        ...Fonts.medium16,
        color: colors.mainTextColor,
    },
    dangerButton: {
        height: 56,
        borderRadius: 12,
        backgroundColor: '#ED5454',
        alignItems: 'center',
        justifyContent: 'center',
        flexDirection: 'row',
        gap: 10,
    },
    dangerButtonText: {
        ...Fonts.medium16,
        color: colors.pureWhite,
    },
    modalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0,0,0,0.56)',
        alignItems: 'center',
        justifyContent: 'center',
        paddingHorizontal: 20,
    },
    modalCard: {
        width: '100%',
        borderRadius: 16,
        backgroundColor: colors.cardBackground,
        padding: 20,
    },
    modalTitle: {
        ...Fonts.medium18,
        color: colors.mainTextColor,
        marginBottom: 8,
    },
    modalDescription: {
        ...Fonts.regular14,
        color: colors.grayColor,
        lineHeight: 21,
        marginBottom: 12,
    },
    modalHint: {
        ...Fonts.medium14,
        color: colors.mainTextColor,
        marginBottom: 10,
    },
    confirmInput: {
        height: 54,
        borderRadius: 12,
        borderWidth: 0.5,
        borderColor: colors.lightGrayColor,
        backgroundColor: colors.backgroundColor,
        paddingHorizontal: 16,
        color: colors.mainTextColor,
        ...Fonts.medium16,
    },
    modalActions: {
        flexDirection: 'row',
        gap: 12,
        marginTop: 18,
    },
    modalSecondaryButton: {
        flex: 1,
        height: 52,
        borderRadius: 12,
        borderWidth: 0.5,
        borderColor: colors.lightGrayColor,
        alignItems: 'center',
        justifyContent: 'center',
    },
    modalSecondaryButtonText: {
        ...Fonts.medium16,
        color: colors.mainTextColor,
    },
    modalDangerButton: {
        flex: 1,
        height: 52,
        borderRadius: 12,
        backgroundColor: '#ED5454',
        alignItems: 'center',
        justifyContent: 'center',
    },
    modalDangerButtonDisabled: {
        opacity: 0.45,
    },
    modalDangerButtonText: {
        ...Fonts.medium16,
        color: colors.pureWhite,
    },
});

const styles = createStyles(lightColors);
export default styles;
