import { StyleSheet } from 'react-native';
import { lightColors } from '../../constants/Theme';
import Fonts from '../../constants/Fonts';
export const createStyles = (colors) => StyleSheet.create({
    mainContainer: {
        flex: 1,
        backgroundColor: colors.cardBackground,
    },
    header: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 20,
        paddingVertical: 15,
        borderBottomWidth: 0.5,
        borderBottomColor: colors.lightGrayColor,
    },
    backButton: {
        width: 44,
        height: 44,
        borderRadius: 22,
        backgroundColor: colors.btnBackgroundColor,
        alignItems: 'center',
        justifyContent: 'center',
    },
    headerTitle: Object.assign(Object.assign({}, Fonts.medium16), { fontSize: 18, color: colors.mainTextColor }),
    notificationButton: {
        width: 44,
        height: 44,
        borderRadius: 22,
        backgroundColor: colors.btnBackgroundColor,
        alignItems: 'center',
        justifyContent: 'center',
    },
    scrollContent: {
        paddingHorizontal: 20,
        paddingTop: 20,
        paddingBottom: 100,
    },
    videoContainer: {
        width: '100%',
        height: 200,
        borderRadius: 10,
        overflow: 'hidden',
        position: 'relative',
    },
    videoPlayer: {
        width: '100%',
        height: '100%',
    },
    playButtonOverlay: {
        position: 'absolute',
        top: '50%',
        left: '50%',
        marginTop: -28,
        marginLeft: -28,
        width: 56,
        height: 56,
        borderRadius: 28,
        backgroundColor: 'rgba(0,0,0,0.25)',
        alignItems: 'center',
        justifyContent: 'center',
    },
    videoInfo: {
        marginTop: 14,
        gap: 8,
    },
    videoInfoRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    videoTitle: Object.assign(Object.assign({}, Fonts.medium16), { color: colors.mainTextColor }),
    locationContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 4,
    },
    locationText: Object.assign(Object.assign({}, Fonts.regular14), { color: colors.subTextColor }),
    durationContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 4,
    },
    durationText: Object.assign(Object.assign({}, Fonts.regular14), { color: colors.subTextColor }),
    dateContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 4,
    },
    dateText: Object.assign(Object.assign({}, Fonts.regular14), { color: colors.subTextColor }),
    sectionTitle: Object.assign(Object.assign({}, Fonts.medium16), { fontSize: 18, color: colors.mainTextColor, marginTop: 16 }),
    receivedLabel: {
        backgroundColor: colors.secondaryColor,
        borderWidth: 0.5,
        borderColor: colors.borderColor,
        borderRadius: 10,
        paddingHorizontal: 12,
        paddingVertical: 6,
    },
    receivedText: Object.assign(Object.assign({}, Fonts.regular14), { color: colors.subTextColor }),
    editRequestsGrid: {
        gap: 16,
    },
    editRequestsRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        flexWrap: 'wrap',
        gap: 12,
    },
    editRequestCard: {
        width: '48%',
        backgroundColor: colors.cardBackground,
        borderWidth: 0.5,
        borderColor: colors.lightGrayColor,
        borderRadius: 10,
        padding: 16,
        gap: 8,
    },
    editRequestHeader: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        justifyContent: 'space-between',
    },
    receiptIconContainer: {
        width: 40,
        height: 40,
        borderRadius: 6,
        backgroundColor: colors.secondaryBlueColor,
        alignItems: 'center',
        justifyContent: 'center',
    },
    editRequestContent: {
        gap: 6,
    },
    editRequestTitle: Object.assign(Object.assign({}, Fonts.medium14), { color: colors.mainTextColor }),
    editRequestMeta: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    metaItem: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 4,
    },
    metaText: Object.assign(Object.assign({}, Fonts.regular12), { color: colors.subTextColor }),
    fixedBadge: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 4,
        backgroundColor: colors.secondaryBlueColor,
        borderRadius: 6,
        paddingHorizontal: 12,
        paddingVertical: 4,
        alignSelf: 'flex-start',
    },
    fixedBadgeText: Object.assign(Object.assign({}, Fonts.regular12), { color: colors.greenColor }),
    pendingBadge: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 4,
        backgroundColor: colors.secondaryBlueColor,
        borderRadius: 6,
        paddingHorizontal: 12,
        paddingVertical: 4,
        alignSelf: 'flex-start',
    },
    pendingBadgeText: Object.assign(Object.assign({}, Fonts.regular12), { color: '#FF8000' }),
    wontFixBadge: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 4,
        backgroundColor: '#FFE9E9',
        borderRadius: 6,
        paddingHorizontal: 12,
        paddingVertical: 4,
        alignSelf: 'flex-start',
    },
    wontFixBadgeText: Object.assign(Object.assign({}, Fonts.regular12), { color: '#FF3B30' }),
    primaryButton: {
        backgroundColor: colors.primaryColor,
        borderRadius: 10,
        height: 54,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 8,
    },
    primaryButtonText: Object.assign(Object.assign({}, Fonts.medium16), { color: colors.whiteColor }),
    loadMoreButton: {
        height: 44,
        borderRadius: 10,
        borderWidth: 0.5,
        borderColor: colors.lightGrayColor,
        alignItems: 'center',
        justifyContent: 'center',
        marginTop: 16,
    },
    loadMoreText: Object.assign(Object.assign({}, Fonts.medium14), { color: colors.mainTextColor }),
    emptyStateContainer: {
        alignItems: 'center',
        paddingVertical: 20,
    },
    emptyStateText: Object.assign(Object.assign({}, Fonts.regular14), { color: colors.grayColor }),
    modalBackdrop: {
        flex: 1,
        backgroundColor: 'rgba(0,0,0,0.35)',
        alignItems: 'center',
        justifyContent: 'center',
        paddingHorizontal: 20,
    },
    modalCard: {
        width: '100%',
        backgroundColor: colors.cardBackground,
        borderRadius: 16,
        padding: 16,
    },
    modalTitle: Object.assign(Object.assign({}, Fonts.medium18), { color: colors.mainTextColor }),
    modalSubtitle: Object.assign(Object.assign({}, Fonts.regular13), { color: colors.grayColor, marginTop: 4, marginBottom: 12 }),
    modalLabel: Object.assign(Object.assign({}, Fonts.medium14), { color: colors.mainTextColor, marginTop: 12, marginBottom: 6 }),
    modalInput: Object.assign(Object.assign({ height: 46, borderRadius: 10, borderWidth: 0.5, borderColor: colors.lightGrayColor, paddingHorizontal: 12 }, Fonts.regular14), { color: colors.mainTextColor, backgroundColor: colors.cardBackground }),
    modalSelectRow: {
        height: 46,
        borderRadius: 10,
        borderWidth: 0.5,
        borderColor: colors.lightGrayColor,
        paddingHorizontal: 12,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        backgroundColor: colors.cardBackground,
    },
    modalSelectText: Object.assign(Object.assign({}, Fonts.regular14), { color: colors.mainTextColor }),
    modalOptionsList: {
        borderWidth: 0.5,
        borderColor: colors.lightGrayColor,
        borderRadius: 10,
        backgroundColor: colors.cardBackground,
        marginTop: 8,
        overflow: 'hidden',
    },
    modalOption: {
        paddingHorizontal: 12,
        paddingVertical: 10,
        borderBottomWidth: 0.5,
        borderBottomColor: colors.lightGrayColor,
    },
    modalOptionText: Object.assign(Object.assign({}, Fonts.regular14), { color: colors.mainTextColor }),
    modalUploadButton: {
        height: 44,
        borderRadius: 10,
        borderWidth: 0.5,
        borderColor: colors.lightGrayColor,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: colors.secondaryColor,
    },
    modalUploadText: Object.assign(Object.assign({}, Fonts.medium14), { color: colors.mainTextColor }),
    modalFileName: Object.assign(Object.assign({}, Fonts.regular12), { color: colors.grayColor, marginTop: 6 }),
    modalButtonRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 12,
        marginTop: 16,
    },
    modalCancelButton: {
        flex: 1,
        height: 46,
        borderRadius: 10,
        borderWidth: 0.5,
        borderColor: colors.lightGrayColor,
        alignItems: 'center',
        justifyContent: 'center',
    },
    modalCancelText: Object.assign(Object.assign({}, Fonts.medium14), { color: colors.grayColor }),
    modalSaveButton: {
        flex: 1,
        height: 46,
        borderRadius: 10,
        backgroundColor: colors.primaryColor,
        alignItems: 'center',
        justifyContent: 'center',
    },
    modalSaveText: Object.assign(Object.assign({}, Fonts.medium14), { color: colors.whiteColor }),
    exampleCard: {
        borderWidth: 0.5,
        borderColor: colors.lightGrayColor,
        borderRadius: 10,
        padding: 16,
        marginTop: 10,
    },
    exampleTitle: Object.assign(Object.assign({}, Fonts.medium14), { color: colors.mainTextColor }),
    exampleText: Object.assign(Object.assign({}, Fonts.regular12), { color: colors.grayColor, marginTop: 6, marginBottom: 8 }),
    statusOption: {
        height: 44,
        borderRadius: 10,
        borderWidth: 0.5,
        borderColor: colors.lightGrayColor,
        alignItems: 'center',
        justifyContent: 'center',
        marginBottom: 8,
    },
    statusOptionActive: {
        borderColor: colors.primaryColor,
        backgroundColor: '#E8F1FF',
    },
    statusOptionText: Object.assign(Object.assign({}, Fonts.medium14), { color: colors.mainTextColor }),
    modalSaveButtonDisabled: {
        backgroundColor: '#B8C7E6',
    },
});
const Styles = createStyles(lightColors);
export default Styles;
