import { StyleSheet } from 'react-native';
import Colors from '../../constants/Colors';
import Fonts from '../../constants/Fonts';

const Styles = StyleSheet.create({
    mainContainer: {
        flex: 1,
        backgroundColor: Colors.whiteColor,
    },
    header: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 20,
        paddingVertical: 16,
        borderBottomWidth: 0.5,
        borderBottomColor: '#DEDEDE',
    },
    backButton: {
        width: 44,
        height: 44,
        borderRadius: 22,
        backgroundColor: '#F5F5F5',
        alignItems: 'center',
        justifyContent: 'center',
    },
    headerTitle: {
        ...Fonts.medium14,
        color: Colors.mainTextColor,
    },
    placeholder: {
        width: 44,
        height: 44,
    },
    content: {
        flex: 1,
        paddingHorizontal: 20,
        paddingTop: 16,
    },
    photoContainer: {
        flex: 1,
        borderRadius: 10,
        overflow: 'hidden',
        marginBottom: 20,
        position: 'relative',
    },
    photoImage: {
        width: '100%',
        height: '100%',
    },
    topRow: {
        position: 'absolute',
        top: 12,
        left: 14,
        right: 14,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    viewsContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 4,
    },
    viewsText: {
        ...Fonts.regular16,
        color: Colors.whiteColor,
    },
    gradientOverlay: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        justifyContent: 'flex-end',
    },
    bottomRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 14,
        paddingBottom: 10,
    },
    photoTitle: {
        ...Fonts.medium16,
        color: Colors.whiteColor,
        flex: 1,
    },
    buyButton: {
        backgroundColor: Colors.primaryColor,
        borderRadius: 8,
        paddingHorizontal: 16,
        paddingVertical: 10,
        width: 97,
        alignItems: 'center',
        justifyContent: 'center',
    },
    buyButtonText: {
        ...Fonts.regular14,
        color: Colors.whiteColor,
    },
    // Modal Styles
    modalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0,0,0,0.5)',
        justifyContent: 'center',
        alignItems: 'center',
    },
    modalContainer: {
        width: 310,
        backgroundColor: Colors.whiteColor,
        borderRadius: 8,
        borderWidth: 0.4,
        borderColor: '#E0ECFE',
        paddingHorizontal: 13,
        paddingVertical: 16,
        alignItems: 'center',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 0 },
        shadowOpacity: 0.25,
        shadowRadius: 119,
        elevation: 10,
    },
    modalImage: {
        width: 276,
        height: 276,
        borderRadius: 8,
    },
    modalInfoRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        width: 259,
        marginTop: 13,
    },
    modalTitle: {
        ...Fonts.medium14,
        color: Colors.mainTextColor,
    },
    modalPrice: {
        ...Fonts.medium14,
        color: Colors.mainTextColor,
    },
    modalDivider: {
        width: '100%',
        height: 0.4,
        backgroundColor: '#E0ECFE',
        marginVertical: 16,
    },
    modalButtonsRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 13,
    },
    cancelButton: {
        backgroundColor: '#ED5454',
        borderRadius: 8,
        paddingHorizontal: 13,
        paddingVertical: 8,
        width: 112,
        alignItems: 'center',
        justifyContent: 'center',
    },
    payButton: {
        backgroundColor: Colors.primaryColor,
        borderRadius: 8,
        paddingHorizontal: 13,
        paddingVertical: 8,
        width: 112,
        alignItems: 'center',
        justifyContent: 'center',
    },
    modalButtonText: {
        fontSize: 11,
        fontFamily: 'Inter-Regular',
        color: Colors.whiteColor,
        lineHeight: 17,
    },
    // Success Modal Styles
    successModalContainer: {
        width: 297,
        height: 192,
        backgroundColor: Colors.whiteColor,
        borderRadius: 10,
        borderWidth: 0.5,
        borderColor: '#E0ECFE',
        paddingHorizontal: 16,
        paddingVertical: 20,
        alignItems: 'center',
        justifyContent: 'space-between',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 0 },
        shadowOpacity: 0.25,
        shadowRadius: 152,
        elevation: 10,
    },
    successIconContainer: {
        alignItems: 'center',
        justifyContent: 'center',
    },
    successTitle: {
        ...Fonts.medium16,
        color: Colors.mainTextColor,
        textAlign: 'center',
        marginTop: 5,
    },
    successSubtitle: {
        fontSize: 10,
        fontFamily: 'Inter-Regular',
        color: '#9B9F9F',
        textAlign: 'center',
        lineHeight: 15,
    },
    downloadButton: {
        backgroundColor: Colors.primaryColor,
        borderRadius: 10,
        paddingHorizontal: 13,
        paddingVertical: 13,
        width: 269,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 6,
    },
    downloadButtonText: {
        ...Fonts.medium14,
        color: Colors.whiteColor,
        fontSize: 13,
    },
    // Failed Modal Styles
    failedModalContainer: {
        width: 297,
        height: 192,
        backgroundColor: Colors.whiteColor,
        borderRadius: 10,
        borderWidth: 0.5,
        borderColor: '#E0ECFE',
        paddingHorizontal: 16,
        paddingVertical: 20,
        alignItems: 'center',
        justifyContent: 'space-between',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 0 },
        shadowOpacity: 0.25,
        shadowRadius: 152,
        elevation: 10,
    },
    failedIconContainer: {
        alignItems: 'center',
        justifyContent: 'center',
    },
    failedTitle: {
        ...Fonts.medium16,
        color: Colors.mainTextColor,
        textAlign: 'center',
        marginTop: 5,
    },
    failedSubtitle: {
        fontSize: 10,
        fontFamily: 'Inter-Regular',
        color: '#9B9F9F',
        textAlign: 'center',
        lineHeight: 15,
    },
    failedButtonsRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 16,
        width: '100%',
    },
    failedCancelButton: {
        backgroundColor: '#ED5454',
        borderRadius: 6,
        paddingHorizontal: 16,
        paddingVertical: 10,
        width: 116,
        alignItems: 'center',
        justifyContent: 'center',
    },
    rechargeButton: {
        backgroundColor: Colors.primaryColor,
        borderRadius: 6,
        paddingHorizontal: 16,
        paddingVertical: 10,
        width: 115,
        alignItems: 'center',
        justifyContent: 'center',
    },
    failedButtonText: {
        ...Fonts.regular14,
        color: Colors.whiteColor,
    },
});

export default Styles;
