import { StyleSheet } from 'react-native';
import Colors from '../../../constants/Colors';
import Fonts from '../../../constants/Fonts';

const styles = StyleSheet.create({
    mainContainer: {
        flex: 1,
        backgroundColor: Colors.whiteColor,
    },
    header: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 20,
        paddingVertical: 16,
        borderBottomWidth: 0.5,
        borderBottomColor: '#DEDEDE',
        backgroundColor: Colors.whiteColor,
    },
    headerButton: {
        width: 44,
        height: 44,
        borderRadius: 22,
        backgroundColor: '#F5F5F5',
        alignItems: 'center',
        justifyContent: 'center',
    },
    headerTitle: {
        ...Fonts.medium18,
        color: '#171717',
    },
    topSection: {
        paddingHorizontal: 20,
        paddingTop: 24,
        paddingBottom: 24,
        borderBottomWidth: 0.5,
        borderBottomColor: '#EDE9FE',
    },
    titleSection: {},
    mainTitle: {
        fontFamily: 'Inter-Bold',
        fontSize: 36,
        fontWeight: '700',
        color: '#101828',
        lineHeight: 45,
        letterSpacing: -0.5,
    },
    subtitle: {
        fontFamily: 'Inter-Regular',
        fontSize: 18,
        fontWeight: '400',
        color: '#4A5565',
        lineHeight: 29,
        letterSpacing: -0.4,
    },
    optionsContainer: {
        flex: 1,
        backgroundColor: Colors.whiteColor,
    },
    optionsContent: {
        paddingHorizontal: 20,
        paddingTop: 32,
    },
    searchOptionCard: {
        backgroundColor: Colors.whiteColor,
        borderWidth: 1,
        borderColor: '#DEDEDE',
        borderRadius: 28,
        padding: 24,
        marginBottom: 16,
        height: 193,
        overflow: 'hidden',
    },
    searchOptionCardSelected: {
        borderColor: '#A684FF',
        borderWidth: 2,
        shadowColor: '#DDD6FF',
        shadowOffset: { width: 0, height: 20 },
        shadowOpacity: 0.5,
        shadowRadius: 25,
        elevation: 8,
    },
    searchOptionContent: {
        flexDirection: 'row',
        alignItems: 'flex-start',
    },
    iconWrapper: {
        position: 'relative',
        width: 64,
        height: 64,
    },
    iconBlurEffect: {
        position: 'absolute',
        width: 76,
        height: 76,
        borderRadius: 16,
        backgroundColor: '#A684FF',
        opacity: 0.51,
        top: -6,
        left: -6,
    },
    iconContainer: {
        width: 64,
        height: 64,
        borderRadius: 16,
        alignItems: 'center',
        justifyContent: 'center',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 10 },
        shadowOpacity: 0.1,
        shadowRadius: 15,
        elevation: 5,
    },
    textContainer: {
        flex: 1,
        marginLeft: 20,
    },
    optionTitle: {
        fontFamily: 'Inter-Bold',
        fontSize: 20,
        fontWeight: '700',
        color: '#101828',
        lineHeight: 25,
        letterSpacing: -0.45,
    },
    optionDescription: {
        fontFamily: 'Inter-Regular',
        fontSize: 16,
        fontWeight: '400',
        color: '#4A5565',
        lineHeight: 26,
        letterSpacing: -0.3,
    },
    badge: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 12,
        paddingVertical: 7,
        borderRadius: 9999,
        alignSelf: 'flex-start',
        borderWidth: 1,
    },
    badgeText: {
        fontFamily: 'Inter-SemiBold',
        fontSize: 14,
        fontWeight: '600',
        lineHeight: 20,
        letterSpacing: -0.15,
    },
    progressBar: {
        position: 'absolute',
        bottom: 0,
        left: 0,
        right: 0,
        height: 6,
    },
    modalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
        justifyContent: 'center',
        alignItems: 'center',
    },
    modalContainer: {
        width: '85%',
        backgroundColor: Colors.whiteColor,
        borderRadius: 20,
        padding: 24,
    },
    filtersModalContainer: {
        width: '85%',
        backgroundColor: Colors.whiteColor,
        borderRadius: 20,
        padding: 24,
    },
    modalTitle: {
        fontFamily: 'Inter-Bold',
        fontSize: 18,
        fontWeight: '700',
        color: '#171717',
        textAlign: 'center',
    },
    contextInputContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: Colors.whiteColor,
        borderWidth: 1,
        borderColor: '#E5E7EB',
        borderRadius: 10,
        paddingHorizontal: 16,
        height: 50,
    },
    contextInput: {
        flex: 1,
        ...Fonts.regular14,
        color: Colors.mainTextColor,
    },
    nextButton: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        height: 50,
        borderRadius: 10,
        gap: 8,
    },
    nextButtonText: {
        ...Fonts.medium16,
        color: Colors.whiteColor,
    },
    filterOption: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        backgroundColor: Colors.whiteColor,
        borderWidth: 1,
        borderColor: '#E5E7EB',
        borderRadius: 10,
        paddingHorizontal: 16,
        height: 54,
        marginBottom: 12,
    },
    filterLabelContainer: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    filterLabel: {
        ...Fonts.regular16,
        color: '#171717',
    },
    checkbox: {
        width: 24,
        height: 24,
        borderRadius: 6,
        borderWidth: 1,
        borderColor: '#E5E7EB',
        alignItems: 'center',
        justifyContent: 'center',
    },
    checkboxChecked: {
        borderWidth: 0,
    },
});

export default styles;
