import { StyleSheet } from 'react-native';
import Fonts from '../../../constants/Fonts';
import { ThemeColors } from '../../../constants/Theme';

export const createStyles = (colors: ThemeColors) => StyleSheet.create({
    mainContainer: {
        flex: 1,
        backgroundColor: colors.backgroundColor,
    },
    header: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 20,
        paddingVertical: 16,
        borderBottomWidth: 0.3,
        borderBottomColor: colors.lightGrayColor,
    },
    headerButton: {
        width: 44,
        height: 44,
        borderRadius: 22,
        backgroundColor: colors.btnBackgroundColor,
        alignItems: 'center',
        justifyContent: 'center',
    },
    headerTitle: {
        ...Fonts.medium18,
        color: colors.mainTextColor,
    },
    content: {
        flex: 1,
        paddingHorizontal: 20,
        paddingTop: 20,
    },
    competitionName: {
        ...Fonts.medium18,
        color: colors.mainTextColor,
    },
    competitionDescription: {
        ...Fonts.regular14,
        color: colors.subTextColor,
    },
    tabsContainer: {
        flexDirection: 'row',
        borderWidth: 0.5,
        borderColor: colors.lightGrayColor,
        borderRadius: 10,
        padding: 8,
        gap: 8,
    },
    tab: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        paddingHorizontal: 16,
        height: 39,
        gap: 8,
        backgroundColor: 'transparent',
        borderRadius: 8,
    },
    tabActive: {
        backgroundColor: colors.secondaryBlueColor,
    },
    tabText: {
        ...Fonts.regular14,
        color: colors.subTextColor,
    },
    tabTextActive: {
        color: colors.mainTextColor,
    },
    sectionHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    sectionTitle: {
        ...Fonts.medium16,
        color: colors.mainTextColor,
    },
    sectionIcons: {
        flexDirection: 'row',
    },
    sectionIconButton: {
        width: 36,
        height: 36,
        borderRadius: 8,
        backgroundColor: colors.primaryColor,
        alignItems: 'center',
        justifyContent: 'center',
    },
    eventCard: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        padding: 16,
        borderWidth: 0.5,
        borderColor: colors.lightGrayColor,
        borderRadius: 10,
        backgroundColor: colors.cardBackground,
        marginBottom: 12,
    },
    eventCardLeft: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 12,
        flex: 1,
    },
    eventThumbnail: {
        width: 44,
        height: 44,
        borderRadius: 10,
        backgroundColor: colors.btnBackgroundColor,
    },
    eventCardName: {
        ...Fonts.medium14,
        color: colors.mainTextColor,
        flexShrink: 1,
    },
    eventCardRight: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
    },
    badge: {
        backgroundColor: colors.btnBackgroundColor,
        paddingHorizontal: 10,
        paddingVertical: 4,
        borderRadius: 6,
    },
    badgeText: {
        ...Fonts.regular12,
        color: colors.subTextColor,
    },
    showAllButton: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        height: 54,
        borderRadius: 10,
        backgroundColor: colors.primaryColor,
        gap: 8,
    },
    showAllButtonText: {
        ...Fonts.medium16,
        color: colors.pureWhite,
    },
    showAllPhotosButton: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        height: 54,
        borderRadius: 10,
        borderWidth: 1,
        borderColor: colors.primaryColor,
        backgroundColor: colors.cardBackground,
        gap: 8,
    },
    showAllPhotosButtonText: {
        ...Fonts.medium16,
        color: colors.primaryColor,
    },
    toggleRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingVertical: 10,
        paddingHorizontal: 12,
        borderWidth: 0.5,
        borderColor: colors.lightGrayColor,
        borderRadius: 10,
        backgroundColor: colors.cardBackground,
    },
    toggleLabel: {
        ...Fonts.medium14,
        color: colors.mainTextColor,
    },
    toggleHint: {
        ...Fonts.regular12,
        color: colors.subTextColor,
        marginTop: 2,
    },
    emptyState: {
        paddingVertical: 18,
        paddingHorizontal: 16,
        borderWidth: 0.5,
        borderColor: colors.lightGrayColor,
        borderRadius: 10,
        backgroundColor: colors.cardBackground,
    },
    emptyStateText: {
        ...Fonts.regular14,
        color: colors.subTextColor,
    },
    courseList: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 12,
    },
    courseCard: {
        width: '48%',
        borderWidth: 0.5,
        borderColor: '#DEDEDE',
        borderRadius: 12,
        padding: 14,
        backgroundColor: '#FFFFFF',
    },
    courseCardActive: {
        borderColor: colors.primaryColor,
        backgroundColor: 'rgba(60, 130, 246, 0.12)',
    },
    courseTitle: {
        ...Fonts.medium16,
        color: colors.mainTextColor,
    },
    courseTitleActive: {
        color: colors.primaryColor,
    },
    courseDescription: {
        ...Fonts.regular12,
        color: '#9B9F9F',
        marginTop: 6,
    },
    courseDescriptionActive: {
        color: colors.primaryColor,
    },
    mapCard: {
        borderWidth: 0.5,
        borderColor: '#DEDEDE',
        borderRadius: 14,
        overflow: 'hidden',
        backgroundColor: '#FFFFFF',
    },
    mapImage: {
        width: '100%',
        height: 220,
    },
    checkpointChip: {
        paddingHorizontal: 14,
        paddingVertical: 10,
        borderRadius: 20,
        borderWidth: 0.5,
        borderColor: '#DEDEDE',
        backgroundColor: '#FFFFFF',
        marginRight: 10,
    },
    checkpointChipText: {
        ...Fonts.medium12,
        color: colors.mainTextColor,
    },
    helperText: {
        ...Fonts.regular12,
        color: '#9B9F9F',
    },
    modalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0,0,0,0.55)',
        justifyContent: 'center',
        paddingHorizontal: 20,
    },
    checkpointModal: {
        backgroundColor: '#FFFFFF',
        borderRadius: 16,
        padding: 20,
    },
    modalTitle: {
        ...Fonts.medium16,
        color: colors.mainTextColor,
        textAlign: 'center',
    },
    modalLabel: {
        ...Fonts.medium12,
        color: colors.mainTextColor,
        marginBottom: 6,
    },
    modalInputRow: {
        borderWidth: 1,
        borderColor: '#E5E7EB',
        borderRadius: 10,
        paddingHorizontal: 12,
        height: 46,
        justifyContent: 'center',
        backgroundColor: '#FFFFFF',
    },
    modalInput: {
        ...Fonts.regular14,
        color: colors.mainTextColor,
        paddingVertical: 0,
    },
    modalErrorText: {
        ...Fonts.regular12,
        color: '#E11D48',
        textAlign: 'center',
    },
    modalPrimaryButton: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        height: 48,
        borderRadius: 10,
        backgroundColor: colors.primaryColor,
        gap: 8,
    },
    modalPrimaryButtonDisabled: {
        opacity: 0.7,
    },
    modalPrimaryButtonText: {
        ...Fonts.medium14,
        color: colors.whiteColor,
    },
    modalSecondaryButton: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        height: 48,
        borderRadius: 10,
        borderWidth: 1,
        borderColor: colors.primaryColor,
        backgroundColor: '#FFFFFF',
        gap: 8,
    },
    modalSecondaryButtonText: {
        ...Fonts.medium14,
        color: colors.primaryColor,
    },
    modalTertiaryButton: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        height: 48,
        borderRadius: 10,
        borderWidth: 1,
        borderColor: '#DEDEDE',
        backgroundColor: '#FFFFFF',
        gap: 8,
    },
    modalTertiaryButtonText: {
        ...Fonts.medium14,
        color: colors.mainTextColor,
    },
});
