import { StyleSheet } from 'react-native';
import Colors from '../../constants/Colors';
import Fonts from '../../constants/Fonts';

const Styles = StyleSheet.create({
    mainContainer: {
        flex: 1,
        backgroundColor: Colors.whiteColor,
    },
    header: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 20,
        paddingVertical: 16,
    },
    headerSpacer: {
        width: 44,
        height: 44,
    },
    backButton: {
        width: 44,
        height: 44,
        borderRadius: 22,
        backgroundColor: '#F5F5F5',
        alignItems: 'center',
        justifyContent: 'center',
    },
    headerTitle: {
        ...Fonts.medium18,
        color: Colors.mainTextColor,
    },
    notificationButton: {
        width: 44,
        height: 44,
        borderRadius: 22,
        backgroundColor: '#F5F5F5',
        alignItems: 'center',
        justifyContent: 'center',
    },
    searchRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 10,
    },
    searchInputContainer: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#F7FAFF',
        borderWidth: 0.5,
        borderColor: '#E0ECFE',
        borderRadius: 10,
        paddingHorizontal: 16,
        height: 54,
    },
    searchInputPill: {
        backgroundColor: '#E8F1FF',
        paddingHorizontal: 10,
        paddingVertical: 6,
        borderRadius: 8,
        marginRight: 8,
    },
    searchInputPillText: {
        ...Fonts.medium12,
        color: Colors.primaryColor,
    },
    searchInput: {
        flex: 1,
        ...Fonts.regular14,
        color: Colors.mainTextColor,
    },
    scrollContent: {
        paddingHorizontal: 20,
        paddingBottom: 40,
    },
    sectionHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginBottom: 16,
    },
    sectionTitle: {
        ...Fonts.medium18,
        color: Colors.mainTextColor,
    },
    viewAllText: {
        ...Fonts.regular14,
        color: '#9B9F9F',
    },
    filterTabsContainer: {
        flexDirection: 'row',
    },
    filterTab: {
        flexDirection: 'row',
        paddingHorizontal: 10,
        paddingVertical: 6,
        borderRadius: 6,
        backgroundColor: '#F5F5F5',
        marginRight: 8,
        height: 32,
        alignItems: 'center',
        justifyContent: 'center',
    },
    filterTabActive: {
        backgroundColor: Colors.primaryColor,
    },
    filterTabText: {
        ...Fonts.regular12,
        color: '#777777',
    },
    filterTabTextActive: {
        color: Colors.whiteColor,
    },
    eventCard: {
        flexDirection: 'row',
        alignItems: 'center',
        padding: 16,
        borderWidth: 0.5,
        borderColor: '#DEDEDE',
        borderRadius: 10,
        backgroundColor: Colors.whiteColor,
        marginBottom: 12,
    },
    eventIconContainer: {
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: '#E8F1FF',
        alignItems: 'center',
        justifyContent: 'center',
    },
    eventContent: {
        flex: 1,
    },
    eventNameRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    eventName: {
        ...Fonts.medium14,
        color: Colors.mainTextColor,
        flex: 1,
    },
    eventTypeBadge: {
        backgroundColor: '#F5F5F5',
        paddingHorizontal: 10,
        paddingVertical: 4,
        borderRadius: 6,
        marginLeft: 8,
    },
    eventTypeBadgeText: {
        ...Fonts.regular12,
        color: '#9B9F9F',
    },
    eventDetails: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    eventDetailItem: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    eventDetailText: {
        ...Fonts.regular12,
        color: '#9B9F9F',
    },
    cardActions: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 12,
        marginTop: 12,
    },
    addMyselfButton: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: Colors.primaryColor,
        borderRadius: 999,
        paddingVertical: 8,
        paddingHorizontal: 18,
        height: 34,
        gap: 6,
    },
    addMyselfButtonText: {
        ...Fonts.regular14,
        color: Colors.whiteColor,
    },
    eventActionRow: {
        alignItems: 'flex-end',
        marginTop: 12,
    },
    viewButton: {
        display: 'none',
    },
    viewButtonText: {
        display: 'none',
    },
    typeFilterRow: {
        gap: 8,
    },
    typeFilterLabel: {
        ...Fonts.medium14,
        color: Colors.mainTextColor,
    },
    typeFilterChips: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 8,
    },
    typeFilterChip: {
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: 6,
        borderWidth: 0.5,
        borderColor: '#DEDEDE',
        backgroundColor: Colors.whiteColor,
    },
    typeFilterChipActive: {
        backgroundColor: Colors.primaryColor,
        borderColor: Colors.primaryColor,
    },
    typeFilterChipText: {
        ...Fonts.regular12,
        color: '#9B9F9F',
    },
    typeFilterChipTextActive: {
        color: Colors.whiteColor,
    },
    activeChipsContainer: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 8,
    },
    activeChip: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: Colors.primaryColor,
        paddingHorizontal: 10,
        paddingVertical: 6,
        borderRadius: 6,
        height: 32,
        gap: 6,
    },
    activeChipText: {
        ...Fonts.regular12,
        color: Colors.whiteColor,
        marginRight: 4,
    },
    timeRangeChip: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: Colors.whiteColor,
        borderWidth: 0.5,
        borderColor: '#DEDEDE',
        paddingHorizontal: 10,
        paddingVertical: 6,
        borderRadius: 6,
        height: 32,
    },
    timeRangeChipActive: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#E8F1FF',
        borderWidth: 0.5,
        borderColor: Colors.primaryColor,
        paddingHorizontal: 10,
        paddingVertical: 6,
        borderRadius: 6,
        gap: 6,
    },
    timeRangeText: {
        ...Fonts.regular12,
        color: '#9B9F9F',
    },
    timeRangeTextActive: {
        ...Fonts.regular12,
        color: Colors.primaryColor,
    },
    modalBackdrop: {
        flex: 1,
        backgroundColor: 'rgba(0,0,0,0.35)',
        alignItems: 'center',
        justifyContent: 'center',
        paddingHorizontal: 20,
    },
    modalCard: {
        width: '100%',
        backgroundColor: Colors.whiteColor,
        borderRadius: 16,
        padding: 16,
    },
    modalHeaderRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        gap: 12,
    },
    modalTitle: {
        ...Fonts.medium18,
        color: Colors.mainTextColor,
    },
    modalHeaderAction: {
        paddingHorizontal: 10,
        paddingVertical: 6,
        borderRadius: 10,
        borderWidth: 1,
        borderColor: Colors.primaryColor,
    },
    modalHeaderActionText: {
        ...Fonts.medium12,
        color: Colors.primaryColor,
    },
    modalSubtitle: {
        ...Fonts.regular13,
        color: Colors.grayColor,
        marginTop: 4,
        marginBottom: 12,
    },
    modalSectionTitle: {
        ...Fonts.medium14,
        color: Colors.mainTextColor,
        marginTop: 12,
        marginBottom: 8,
    },
    modalChipsGrid: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 10,
    },
    modalChip: {
        backgroundColor: Colors.whiteColor,
        borderRadius: 16,
        borderWidth: 0.5,
        borderColor: '#E0ECFE',
        paddingHorizontal: 12,
        height: 32,
        alignItems: 'center',
        justifyContent: 'center',
    },
    modalChipActive: {
        backgroundColor: Colors.primaryColor,
        borderColor: Colors.primaryColor,
    },
    modalChipText: {
        ...Fonts.regular12,
        color: Colors.grayColor,
    },
    modalChipTextActive: {
        color: Colors.whiteColor,
    },
    modalChestInput: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#F7FAFF',
        borderRadius: 10,
        paddingHorizontal: 12,
        height: 46,
        borderWidth: 0.5,
        borderColor: '#E0ECFE',
        gap: 8,
    },
    modalChestTextInput: {
        flex: 1,
        ...Fonts.regular14,
        color: Colors.mainTextColor,
        padding: 0,
    },
    defaultChestRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginTop: 10,
        gap: 8,
    },
    defaultChestBox: {
        width: 18,
        height: 18,
        borderRadius: 5,
        borderWidth: 1,
        borderColor: '#D6D6D6',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: Colors.whiteColor,
    },
    defaultChestBoxActive: {
        backgroundColor: '#2F6BFF',
        borderColor: '#2F6BFF',
    },
    defaultChestCheck: {
        color: Colors.whiteColor,
        fontSize: 12,
        fontWeight: '700',
    },
    defaultChestText: {
        ...Fonts.regular12,
        color: Colors.grayColor,
    },
    modalButtonsRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginTop: 16,
        gap: 12,
    },
    modalCancelButton: {
        flex: 1,
        height: 46,
        borderRadius: 10,
        borderWidth: 1,
        borderColor: '#E0ECFE',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: Colors.whiteColor,
    },
    modalCancelText: {
        ...Fonts.medium14,
        color: Colors.grayColor,
    },
    modalConfirmButton: {
        flex: 1,
        height: 46,
        borderRadius: 10,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: Colors.primaryColor,
    },
    modalConfirmButtonDisabled: {
        backgroundColor: '#B8C7E6',
    },
    modalConfirmText: {
        ...Fonts.medium14,
        color: Colors.whiteColor,
    },
    modalConfirmTextDisabled: {
        color: Colors.whiteColor,
    },
    // Filter styles
    filtersContainer: {
        paddingHorizontal: 20,
        marginBottom: 16,
        gap: 16,
    },
    filterChipsRow: {
        flexDirection: 'row',
        gap: 6,
    },
    filterChip: {
        backgroundColor: '#F5F5F5',
        borderRadius: 6,
        paddingHorizontal: 10,
        height: 32,
        alignItems: 'center',
        justifyContent: 'center',
    },
    filterChipActive: {
        backgroundColor: Colors.primaryColor,
    },
    filterChipText: {
        ...Fonts.regular12,
        color: '#777777',
    },
    filterChipTextActive: {
        color: Colors.whiteColor,
    },
    activeFiltersRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    activeFilterChip: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: Colors.primaryColor,
        borderRadius: 6,
        paddingHorizontal: 10,
        height: 32,
        gap: 4,
    },
    activeFilterText: {
        ...Fonts.regular12,
        color: Colors.whiteColor,
    },
    timeRangeButton: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: Colors.whiteColor,
        borderRadius: 6,
        paddingHorizontal: 10,
        height: 32,
        gap: 4,
        borderWidth: 0.5,
        borderColor: '#DEDEDE',
    },
    timeRangeText: {
        ...Fonts.regular12,
        color: '#9B9F9F',
    },
    eventsCountBadge: {
        backgroundColor: '#F5F5F5',
        borderRadius: 6,
        paddingHorizontal: 12,
        paddingVertical: 6,
    },
    eventsCountText: {
        ...Fonts.regular14,
        color: '#9B9F9F',
    },
    dateModalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
        justifyContent: 'center',
        alignItems: 'center',
    },
    dateModalContainer: {
        backgroundColor: Colors.whiteColor,
        borderRadius: 16,
        padding: 20,
        maxHeight: '85%',
    },
    dateModalTitle: {
        ...Fonts.medium16,
        color: Colors.mainTextColor,
        textAlign: 'center',
    },
    quickRangeRow: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 8,
    },
    quickRangeChip: {
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: 999,
        borderWidth: 0.5,
        borderColor: '#DEDEDE',
        backgroundColor: '#F7FAFF',
    },
    quickRangeChipText: {
        ...Fonts.regular12,
        color: Colors.mainTextColor,
    },
    rangeHeaderRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        gap: 10,
    },
    rangePill: {
        flex: 1,
        backgroundColor: '#F7FAFF',
        borderRadius: 10,
        paddingHorizontal: 12,
        paddingVertical: 8,
        borderWidth: 0.5,
        borderColor: '#DEDEDE',
    },
    rangePillLabel: {
        ...Fonts.regular12,
        color: '#9B9F9F',
    },
    rangePillValue: {
        ...Fonts.medium14,
        color: Colors.mainTextColor,
        marginTop: 2,
    },
    calendarContainer: {
        height: 320,
        alignSelf: 'center',
    },
    dateModalButtonRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        gap: 12,
    },
    dateModalCancelButton: {
        flex: 1,
        height: 48,
        borderRadius: 10,
        borderWidth: 0.5,
        borderColor: '#DEDEDE',
        alignItems: 'center',
        justifyContent: 'center',
    },
    dateModalCancelText: {
        ...Fonts.medium14,
        color: '#9B9F9F',
    },
    dateModalSubmitButton: {
        flex: 1,
        height: 48,
        borderRadius: 10,
        backgroundColor: Colors.primaryColor,
        alignItems: 'center',
        justifyContent: 'center',
    },
    dateModalSubmitButtonDisabled: {
        backgroundColor: '#B0D4FF',
    },
    dateModalSubmitText: {
        ...Fonts.medium14,
        color: Colors.whiteColor,
    },
});

export default Styles;
