import React, { createContext, useContext, useEffect, useMemo, useState, ReactNode } from 'react';
import AsyncStorage from '@react-native-async-storage/async-storage';

export type LanguageCode = 'en' | 'nl' | 'fr' | 'de' | 'es' | 'it' | 'pt';

const LANGUAGE_STORAGE_KEY = '@app_language';

const translations: Record<LanguageCode, Record<string, string>> = {
    en: {
        notifications: 'Notifications',
        notificationTitle: 'You have New Notification',
        notificationDescription: 'Lorem ipsum dolor sit amet contestre...',
        new: 'New',
        details: 'Details',
        events: 'Events',
        availableEvents: 'Available Events',
        competition: 'Competition',
        location: 'Location',
        typeCompetition: 'Type competition...',
        typeLocation: 'Type location...',
        competitionType: 'Competition type',
        selectDateRange: 'Select date range',
        thisWeek: 'This week',
        thisMonth: 'This month',
        thisYear: 'This year',
        all: 'All',
        trackAndField: 'Track&Field',
        roadAndTrail: 'Road&Trail',
        selectDate: 'Select date',
        dateOfBirth: 'Date of Birth',
        currentDateOfBirth: 'Current date of birth',
        selectDateOfBirth: 'Select date of birth',
        edit: 'Edit',
        cancel: 'Cancel',
        save: 'Save',
        apply: 'Apply',
        translate: 'Translate',
        showOriginal: 'Show original',
        showTranslation: 'Show translation',
        blogDetails: 'Blog Details',
        read: 'read',
        share: 'Share',
        media: 'Media',
        subscribeToEvent: 'Subscribe to event',
        viewCompetition: 'View competition',
        selectDisciplineChest: 'Select disciplines and chest number.',
        disciplines: 'Disciplines',
        notificationsFor: 'Notifications for',
        chestNumber: 'Chest number',
        enterChestNumber: 'Enter Chest Number',
        useDefaultNumber: 'Use default number',
        continue: 'Continue',
        year: 'Year',
        start: 'Start',
        end: 'End',
        settings: 'Settings',
        appearance: 'Appearance',
        lightMode: 'Light mode',
        darkMode: 'Dark mode',
        settingsSection: 'Settings',
        pushNotifications: 'Push Notifications',
        language: 'Language',
        account: 'Account',
        authentication: 'Authentication',
        other: 'Other',
        paymentMethod: 'Payment Method',
        subscription: 'Subscription',
        termsOfService: 'Terms of Service',
        help: 'Help',
        deletePauseAccount: 'Delete/Pause your account',
        rightToBeForgotten: 'Right to be Forgotten',
        privacySettings: 'Privacy Settings',
        ghostMode: 'Ghost Mode',
        chooseLanguage: 'Choose language',
        men: 'Men',
        women: 'Women',
        junior: 'Junior',
        cadet: 'Cadet',
        master: 'Master',
        senior: 'Senior',
    },
    nl: {
        notifications: 'Meldingen',
        notificationTitle: 'Je hebt een nieuwe melding',
        notificationDescription: 'Lorem ipsum dolor sit amet contestre...',
        new: 'Nieuw',
        details: 'Details',
        events: 'Evenementen',
        availableEvents: 'Beschikbare evenementen',
        competition: 'Competitie',
        location: 'Locatie',
        typeCompetition: 'Typ competitie...',
        typeLocation: 'Typ locatie...',
        competitionType: 'Competitietype',
        selectDateRange: 'Selecteer datumbereik',
        thisWeek: 'Deze week',
        thisMonth: 'Deze maand',
        thisYear: 'Dit jaar',
        all: 'Alle',
        trackAndField: 'Atletiek',
        roadAndTrail: 'Weg & Trail',
        selectDate: 'Selecteer datum',
        dateOfBirth: 'Geboortedatum',
        currentDateOfBirth: 'Huidige geboortedatum',
        selectDateOfBirth: 'Selecteer geboortedatum',
        edit: 'Bewerken',
        cancel: 'Annuleren',
        save: 'Opslaan',
        apply: 'Toepassen',
        translate: 'Vertalen',
        showOriginal: 'Toon origineel',
        showTranslation: 'Toon vertaling',
        blogDetails: 'Blogdetails',
        read: 'gelezen',
        share: 'Delen',
        media: 'Media',
        subscribeToEvent: 'Inschrijven voor evenement',
        viewCompetition: 'Bekijk competitie',
        selectDisciplineChest: 'Selecteer disciplines en borstnummer.',
        disciplines: 'Disciplines',
        notificationsFor: 'Meldingen voor',
        chestNumber: 'Borstnummer',
        enterChestNumber: 'Voer borstnummer in',
        useDefaultNumber: 'Gebruik standaardnummer',
        continue: 'Doorgaan',
        year: 'Jaar',
        start: 'Start',
        end: 'Einde',
        settings: 'Instellingen',
        appearance: 'Weergave',
        lightMode: 'Lichte modus',
        darkMode: 'Donkere modus',
        settingsSection: 'Instellingen',
        pushNotifications: 'Pushmeldingen',
        language: 'Taal',
        account: 'Account',
        authentication: 'Authenticatie',
        other: 'Overig',
        paymentMethod: 'Betaalmethode',
        subscription: 'Abonnement',
        termsOfService: 'Servicevoorwaarden',
        help: 'Hulp',
        deletePauseAccount: 'Account verwijderen/pauzeren',
        rightToBeForgotten: 'Recht om vergeten te worden',
        privacySettings: 'Privacy-instellingen',
        ghostMode: 'Spookmodus',
        chooseLanguage: 'Kies taal',
        men: 'Mannen',
        women: 'Vrouwen',
        junior: 'Junior',
        cadet: 'Cadet',
        master: 'Master',
        senior: 'Senior',
    },
    fr: {
        notifications: 'Notifications',
        notificationTitle: 'Vous avez une nouvelle notification',
        notificationDescription: 'Lorem ipsum dolor sit amet contestre...',
        new: 'Nouveau',
        details: 'Détails',
        events: 'Événements',
        availableEvents: 'Événements disponibles',
        competition: 'Compétition',
        location: 'Lieu',
        typeCompetition: 'Saisir une compétition...',
        typeLocation: 'Saisir un lieu...',
        competitionType: 'Type de compétition',
        selectDateRange: 'Sélectionner une période',
        thisWeek: 'Cette semaine',
        thisMonth: 'Ce mois-ci',
        thisYear: 'Cette année',
        all: 'Tout',
        trackAndField: 'Athlétisme',
        roadAndTrail: 'Route & Trail',
        selectDate: 'Sélectionner une date',
        dateOfBirth: 'Date de naissance',
        currentDateOfBirth: 'Date de naissance actuelle',
        selectDateOfBirth: 'Sélectionnez la date de naissance',
        edit: 'Modifier',
        cancel: 'Annuler',
        save: 'Enregistrer',
        apply: 'Appliquer',
        translate: 'Traduire',
        showOriginal: 'Afficher l’original',
        showTranslation: 'Afficher la traduction',
        blogDetails: 'Détails du blog',
        read: 'lu',
        share: 'Partager',
        media: 'Médias',
        subscribeToEvent: "S'inscrire à l'événement",
        viewCompetition: 'Voir la compétition',
        selectDisciplineChest: 'Sélectionnez les disciplines et le numéro de dossard.',
        disciplines: 'Disciplines',
        notificationsFor: 'Notifications pour',
        chestNumber: 'Numéro de dossard',
        enterChestNumber: 'Saisir le numéro de dossard',
        useDefaultNumber: 'Utiliser le numéro par défaut',
        continue: 'Continuer',
        year: 'Année',
        start: 'Début',
        end: 'Fin',
        settings: 'Paramètres',
        appearance: 'Apparence',
        lightMode: 'Mode clair',
        darkMode: 'Mode sombre',
        settingsSection: 'Paramètres',
        pushNotifications: 'Notifications push',
        language: 'Langue',
        account: 'Compte',
        authentication: 'Authentification',
        other: 'Autres',
        paymentMethod: 'Moyen de paiement',
        subscription: 'Abonnement',
        termsOfService: 'Conditions d’utilisation',
        help: 'Aide',
        deletePauseAccount: 'Supprimer/Suspendre votre compte',
        rightToBeForgotten: 'Droit à l’oubli',
        privacySettings: 'Paramètres de confidentialité',
        ghostMode: 'Mode fantôme',
        chooseLanguage: 'Choisir la langue',
        men: 'Hommes',
        women: 'Femmes',
        junior: 'Junior',
        cadet: 'Cadet',
        master: 'Master',
        senior: 'Senior',
    },
    de: {
        notifications: 'Benachrichtigungen',
        notificationTitle: 'Sie haben eine neue Benachrichtigung',
        notificationDescription: 'Lorem ipsum dolor sit amet contestre...',
        new: 'Neu',
        details: 'Details',
        events: 'Events',
        availableEvents: 'Verfügbare Events',
        competition: 'Wettbewerb',
        location: 'Ort',
        typeCompetition: 'Wettbewerb eingeben...',
        typeLocation: 'Ort eingeben...',
        competitionType: 'Wettbewerbstyp',
        selectDateRange: 'Datumsbereich wählen',
        thisWeek: 'Diese Woche',
        thisMonth: 'Dieser Monat',
        thisYear: 'Dieses Jahr',
        all: 'Alle',
        trackAndField: 'Leichtathletik',
        roadAndTrail: 'Straße & Trail',
        selectDate: 'Datum auswählen',
        dateOfBirth: 'Geburtsdatum',
        currentDateOfBirth: 'Aktuelles Geburtsdatum',
        selectDateOfBirth: 'Geburtsdatum auswählen',
        edit: 'Bearbeiten',
        cancel: 'Abbrechen',
        save: 'Speichern',
        apply: 'Anwenden',
        translate: 'Übersetzen',
        showOriginal: 'Original anzeigen',
        showTranslation: 'Übersetzung anzeigen',
        blogDetails: 'Blogdetails',
        read: 'gelesen',
        share: 'Teilen',
        media: 'Medien',
        subscribeToEvent: 'Für Event anmelden',
        viewCompetition: 'Wettbewerb ansehen',
        selectDisciplineChest: 'Disziplinen und Startnummer auswählen.',
        disciplines: 'Disziplinen',
        notificationsFor: 'Benachrichtigungen für',
        chestNumber: 'Startnummer',
        enterChestNumber: 'Startnummer eingeben',
        useDefaultNumber: 'Standardnummer verwenden',
        continue: 'Weiter',
        year: 'Jahr',
        settings: 'Einstellungen',
        appearance: 'Darstellung',
        lightMode: 'Heller Modus',
        darkMode: 'Dunkler Modus',
        settingsSection: 'Einstellungen',
        pushNotifications: 'Push-Benachrichtigungen',
        language: 'Sprache',
        account: 'Konto',
        authentication: 'Authentifizierung',
        other: 'Sonstiges',
        paymentMethod: 'Zahlungsmethode',
        subscription: 'Abonnement',
        termsOfService: 'Nutzungsbedingungen',
        help: 'Hilfe',
        deletePauseAccount: 'Konto löschen/pausieren',
        rightToBeForgotten: 'Recht auf Vergessenwerden',
        privacySettings: 'Datenschutzeinstellungen',
        ghostMode: 'Geistermodus',
        chooseLanguage: 'Sprache wählen',
        men: 'Männer',
        women: 'Frauen',
        junior: 'Junior',
        cadet: 'Kadet',
        master: 'Master',
        senior: 'Senior',
    },
    es: {
        notifications: 'Notificaciones',
        notificationTitle: 'Tienes una nueva notificación',
        notificationDescription: 'Lorem ipsum dolor sit amet contestre...',
        new: 'Nuevo',
        details: 'Detalles',
        events: 'Eventos',
        availableEvents: 'Eventos disponibles',
        competition: 'Competición',
        location: 'Ubicación',
        typeCompetition: 'Escribe competición...',
        typeLocation: 'Escribe ubicación...',
        competitionType: 'Tipo de competición',
        selectDateRange: 'Seleccionar rango de fechas',
        thisWeek: 'Esta semana',
        thisMonth: 'Este mes',
        thisYear: 'Este año',
        all: 'Todos',
        trackAndField: 'Atletismo',
        roadAndTrail: 'Ruta y trail',
        selectDate: 'Seleccionar fecha',
        dateOfBirth: 'Fecha de nacimiento',
        currentDateOfBirth: 'Fecha de nacimiento actual',
        selectDateOfBirth: 'Seleccionar fecha de nacimiento',
        edit: 'Editar',
        cancel: 'Cancelar',
        save: 'Guardar',
        apply: 'Aplicar',
        translate: 'Traducir',
        showOriginal: 'Mostrar original',
        showTranslation: 'Mostrar traducción',
        blogDetails: 'Detalles del blog',
        read: 'leído',
        share: 'Compartir',
        media: 'Medios',
        subscribeToEvent: 'Suscribirse al evento',
        viewCompetition: 'Ver competición',
        selectDisciplineChest: 'Selecciona disciplinas y número de dorsal.',
        disciplines: 'Disciplinas',
        notificationsFor: 'Notificaciones para',
        chestNumber: 'Número de dorsal',
        enterChestNumber: 'Ingrese número de dorsal',
        useDefaultNumber: 'Usar número por defecto',
        continue: 'Continuar',
        year: 'Año',
        settings: 'Configuración',
        appearance: 'Apariencia',
        lightMode: 'Modo claro',
        darkMode: 'Modo oscuro',
        settingsSection: 'Configuración',
        pushNotifications: 'Notificaciones push',
        language: 'Idioma',
        account: 'Cuenta',
        authentication: 'Autenticación',
        other: 'Otros',
        paymentMethod: 'Método de pago',
        subscription: 'Suscripción',
        termsOfService: 'Términos de servicio',
        help: 'Ayuda',
        deletePauseAccount: 'Eliminar/Pausar tu cuenta',
        rightToBeForgotten: 'Derecho al olvido',
        privacySettings: 'Configuración de privacidad',
        ghostMode: 'Modo fantasma',
        chooseLanguage: 'Elegir idioma',
        men: 'Hombres',
        women: 'Mujeres',
        junior: 'Junior',
        cadet: 'Cadete',
        master: 'Master',
        senior: 'Senior',
    },
    it: {
        notifications: 'Notifiche',
        notificationTitle: 'Hai una nuova notifica',
        notificationDescription: 'Lorem ipsum dolor sit amet contestre...',
        new: 'Nuovo',
        details: 'Dettagli',
        events: 'Eventi',
        availableEvents: 'Eventi disponibili',
        competition: 'Competizione',
        location: 'Luogo',
        typeCompetition: 'Digita competizione...',
        typeLocation: 'Digita luogo...',
        competitionType: 'Tipo di competizione',
        selectDateRange: 'Seleziona intervallo date',
        thisWeek: 'Questa settimana',
        thisMonth: 'Questo mese',
        thisYear: 'Quest’anno',
        all: 'Tutti',
        trackAndField: 'Atletica',
        roadAndTrail: 'Strada & Trail',
        selectDate: 'Seleziona data',
        dateOfBirth: 'Data di nascita',
        currentDateOfBirth: 'Data di nascita attuale',
        selectDateOfBirth: 'Seleziona data di nascita',
        edit: 'Modifica',
        cancel: 'Annulla',
        save: 'Salva',
        apply: 'Applica',
        translate: 'Traduci',
        showOriginal: 'Mostra originale',
        showTranslation: 'Mostra traduzione',
        blogDetails: 'Dettagli blog',
        read: 'letto',
        share: 'Condividi',
        media: 'Media',
        subscribeToEvent: "Iscriviti all'evento",
        viewCompetition: 'Vedi competizione',
        selectDisciplineChest: 'Seleziona discipline e pettorale.',
        disciplines: 'Discipline',
        notificationsFor: 'Notifiche per',
        chestNumber: 'Numero pettorale',
        enterChestNumber: 'Inserisci numero pettorale',
        useDefaultNumber: 'Usa numero predefinito',
        continue: 'Continua',
        year: 'Anno',
        settings: 'Impostazioni',
        appearance: 'Aspetto',
        lightMode: 'Modalità chiara',
        darkMode: 'Modalità scura',
        settingsSection: 'Impostazioni',
        pushNotifications: 'Notifiche push',
        language: 'Lingua',
        account: 'Account',
        authentication: 'Autenticazione',
        other: 'Altro',
        paymentMethod: 'Metodo di pagamento',
        subscription: 'Abbonamento',
        termsOfService: 'Termini di servizio',
        help: 'Aiuto',
        deletePauseAccount: 'Elimina/Sospendi account',
        rightToBeForgotten: 'Diritto all’oblio',
        privacySettings: 'Impostazioni privacy',
        ghostMode: 'Modalità fantasma',
        chooseLanguage: 'Scegli lingua',
        men: 'Uomini',
        women: 'Donne',
        junior: 'Junior',
        cadet: 'Cadetto',
        master: 'Master',
        senior: 'Senior',
    },
    pt: {
        notifications: 'Notificações',
        notificationTitle: 'Você tem uma nova notificação',
        notificationDescription: 'Lorem ipsum dolor sit amet contestre...',
        new: 'Novo',
        details: 'Detalhes',
        events: 'Eventos',
        availableEvents: 'Eventos disponíveis',
        competition: 'Competição',
        location: 'Local',
        typeCompetition: 'Digite competição...',
        typeLocation: 'Digite local...',
        competitionType: 'Tipo de competição',
        selectDateRange: 'Selecionar intervalo de datas',
        thisWeek: 'Esta semana',
        thisMonth: 'Este mês',
        thisYear: 'Este ano',
        all: 'Todos',
        trackAndField: 'Atletismo',
        roadAndTrail: 'Estrada & Trail',
        selectDate: 'Selecionar data',
        dateOfBirth: 'Data de nascimento',
        currentDateOfBirth: 'Data de nascimento atual',
        selectDateOfBirth: 'Selecione a data de nascimento',
        edit: 'Editar',
        cancel: 'Cancelar',
        save: 'Salvar',
        apply: 'Aplicar',
        translate: 'Traduzir',
        showOriginal: 'Mostrar original',
        showTranslation: 'Mostrar tradução',
        blogDetails: 'Detalhes do blog',
        read: 'lido',
        share: 'Compartilhar',
        media: 'Mídia',
        subscribeToEvent: 'Inscrever-se no evento',
        viewCompetition: 'Ver competição',
        selectDisciplineChest: 'Selecione disciplinas e número de peito.',
        disciplines: 'Disciplinas',
        notificationsFor: 'Notificações para',
        chestNumber: 'Número de peito',
        enterChestNumber: 'Digite o número de peito',
        useDefaultNumber: 'Usar número padrão',
        continue: 'Continuar',
        year: 'Ano',
        settings: 'Configurações',
        appearance: 'Aparência',
        lightMode: 'Modo claro',
        darkMode: 'Modo escuro',
        settingsSection: 'Configurações',
        pushNotifications: 'Notificações push',
        language: 'Idioma',
        account: 'Conta',
        authentication: 'Autenticação',
        other: 'Outros',
        paymentMethod: 'Método de pagamento',
        subscription: 'Assinatura',
        termsOfService: 'Termos de serviço',
        help: 'Ajuda',
        deletePauseAccount: 'Excluir/Pausar sua conta',
        rightToBeForgotten: 'Direito ao esquecimento',
        privacySettings: 'Configurações de privacidade',
        ghostMode: 'Modo fantasma',
        chooseLanguage: 'Escolher idioma',
        men: 'Homens',
        women: 'Mulheres',
        junior: 'Junior',
        cadet: 'Cadete',
        master: 'Master',
        senior: 'Senior',
    },
};

const translationWordMap: Record<LanguageCode, Record<string, string>> = {
    en: {},
    nl: {
        the: 'de',
        and: 'en',
        to: 'naar',
        of: 'van',
        in: 'in',
        for: 'voor',
        with: 'met',
        you: 'jij',
        your: 'jouw',
        this: 'dit',
        that: 'dat',
        is: 'is',
        are: 'zijn',
        was: 'was',
        were: 'waren',
        on: 'op',
        from: 'van',
        at: 'bij',
        as: 'als',
        a: 'een',
    },
    fr: {
        the: 'le',
        and: 'et',
        to: 'à',
        of: 'de',
        in: 'dans',
        for: 'pour',
        with: 'avec',
        you: 'vous',
        your: 'votre',
        this: 'ce',
        that: 'cela',
        is: 'est',
        are: 'sont',
        was: 'était',
        were: 'étaient',
        on: 'sur',
        from: 'de',
        at: 'à',
        as: 'comme',
        a: 'un',
    },
    de: {
        the: 'der',
        and: 'und',
        to: 'zu',
        of: 'von',
        in: 'in',
        for: 'für',
        with: 'mit',
        you: 'du',
        your: 'dein',
        this: 'dies',
        that: 'das',
        is: 'ist',
        are: 'sind',
        was: 'war',
        were: 'waren',
        on: 'auf',
        from: 'von',
        at: 'bei',
        as: 'als',
        a: 'ein',
    },
    es: {
        the: 'el',
        and: 'y',
        to: 'a',
        of: 'de',
        in: 'en',
        for: 'para',
        with: 'con',
        you: 'tú',
        your: 'tu',
        this: 'este',
        that: 'ese',
        is: 'es',
        are: 'son',
        was: 'fue',
        were: 'eran',
        on: 'en',
        from: 'de',
        at: 'en',
        as: 'como',
        a: 'un',
    },
    it: {
        the: 'il',
        and: 'e',
        to: 'a',
        of: 'di',
        in: 'in',
        for: 'per',
        with: 'con',
        you: 'tu',
        your: 'tuo',
        this: 'questo',
        that: 'quello',
        is: 'è',
        are: 'sono',
        was: 'era',
        were: 'erano',
        on: 'su',
        from: 'da',
        at: 'a',
        as: 'come',
        a: 'un',
    },
    pt: {
        the: 'o',
        and: 'e',
        to: 'para',
        of: 'de',
        in: 'em',
        for: 'para',
        with: 'com',
        you: 'você',
        your: 'seu',
        this: 'este',
        that: 'esse',
        is: 'é',
        are: 'são',
        was: 'foi',
        were: 'eram',
        on: 'em',
        from: 'de',
        at: 'em',
        as: 'como',
        a: 'um',
    },
};

const languageOptions: Array<{ code: LanguageCode; label: string }> = [
    { code: 'en', label: 'English' },
    { code: 'nl', label: 'Nederlands' },
    { code: 'fr', label: 'Français' },
    { code: 'de', label: 'Deutsch' },
    { code: 'es', label: 'Español' },
    { code: 'it', label: 'Italiano' },
    { code: 'pt', label: 'Português' },
];

interface LanguageContextType {
    language: LanguageCode;
    setLanguage: (code: LanguageCode) => void;
    t: (key: string) => string;
    translateText: (text: string) => string;
    languages: Array<{ code: LanguageCode; label: string }>;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

interface LanguageProviderProps {
    children: ReactNode;
}

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
    const [language, setLanguageState] = useState<LanguageCode>('en');
    const [isLoading, setIsLoading] = useState(true);

    useEffect(() => {
        const loadLanguage = async () => {
            try {
                const stored = await AsyncStorage.getItem(LANGUAGE_STORAGE_KEY);
                if (stored && translations[stored as LanguageCode]) {
                    setLanguageState(stored as LanguageCode);
                }
            } catch {
                // ignore
            } finally {
                setIsLoading(false);
            }
        };
        loadLanguage();
    }, []);

    const setLanguage = async (code: LanguageCode) => {
        setLanguageState(code);
        try {
            await AsyncStorage.setItem(LANGUAGE_STORAGE_KEY, code);
        } catch {
            // ignore
        }
    };

    const t = (key: string) => {
        return translations[language]?.[key] ?? translations.en[key] ?? key;
    };

    const translateText = (text: string) => {
        if (!text) return text;
        if (language === 'en') return text;
        const map = translationWordMap[language];
        if (!map) return text;
        return text.replace(/\b[A-Za-z']+\b/g, (word) => {
            const lower = word.toLowerCase();
            const replacement = map[lower];
            if (!replacement) return word;
            if (word[0] === word[0].toUpperCase()) {
                return replacement.charAt(0).toUpperCase() + replacement.slice(1);
            }
            return replacement;
        });
    };

    const value = useMemo(
        () => ({
            language,
            setLanguage,
            t,
            translateText,
            languages: languageOptions,
        }),
        [language],
    );

    if (isLoading) {
        return null;
    }

    return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
};

export const useLanguage = (): LanguageContextType => {
    const context = useContext(LanguageContext);
    if (!context) {
        throw new Error('useLanguage must be used within a LanguageProvider');
    }
    return context;
};

export default LanguageContext;
