import { StyleSheet } from 'react-native';
import Fonts from '../../constants/Fonts';
import type { ThemeColors } from '../../constants/Theme';

export const createStyles = (colors: ThemeColors) =>
    StyleSheet.create({
        mainContainer: {
            flex: 1,
            backgroundColor: colors.backgroundColor,
        },
        header: {
            flexDirection: 'row',
            alignItems: 'center',
            justifyContent: 'space-between',
            paddingHorizontal: 20,
            paddingVertical: 16,
            borderBottomWidth: 0.5,
            borderBottomColor: colors.lightGrayColor,
        },
        headerButton: {
            width: 44,
            height: 44,
            borderRadius: 22,
            backgroundColor: colors.btnBackgroundColor,
            alignItems: 'center',
            justifyContent: 'center',
        },
        headerTitle: {
            ...Fonts.medium18,
            color: colors.mainTextColor,
        },
        scrollContent: {
            paddingHorizontal: 20,
            paddingTop: 24,
        },
        fieldBlock: {
            marginBottom: 16,
        },
        fieldLabel: {
            ...Fonts.regular12,
            color: colors.grayColor,
            marginBottom: 6,
        },
        sectionHeaderRow: {
            flexDirection: 'row',
            alignItems: 'center',
            justifyContent: 'space-between',
            marginBottom: 6,
        },
        sectionTitle: {
            ...Fonts.semibold14,
            color: colors.mainTextColor,
        },
        sectionAction: {
            borderWidth: 1,
            borderColor: colors.lightGrayColor,
            backgroundColor: colors.btnBackgroundColor,
            borderRadius: 999,
            paddingHorizontal: 12,
            paddingVertical: 6,
        },
        sectionActionText: {
            ...Fonts.semibold12,
            color: colors.primaryColor,
        },
        inlineHeader: {
            flexDirection: 'row',
            alignItems: 'center',
            justifyContent: 'space-between',
            marginBottom: 6,
        },
        inlineAction: {
            paddingHorizontal: 10,
            paddingVertical: 6,
            borderRadius: 10,
            backgroundColor: colors.btnBackgroundColor,
        },
        inlineActionText: {
            ...Fonts.medium12,
            color: colors.primaryColor,
        },
        dateButton: {
            flexDirection: 'row',
            alignItems: 'center',
            gap: 8,
            borderWidth: 1,
            borderColor: colors.lightGrayColor,
            borderRadius: 12,
            paddingHorizontal: 12,
            paddingVertical: 12,
            backgroundColor: colors.btnBackgroundColor,
        },
        dateText: {
            ...Fonts.regular14,
            color: colors.mainTextColor,
        },
        fieldInput: {
            borderWidth: 1,
            borderColor: colors.lightGrayColor,
            borderRadius: 12,
            paddingHorizontal: 12,
            paddingVertical: 12,
            ...Fonts.regular14,
            color: colors.mainTextColor,
            backgroundColor: colors.btnBackgroundColor,
        },
        fieldTextarea: {
            minHeight: 100,
            textAlignVertical: 'top',
        },
        helperText: {
            ...Fonts.regular12,
            color: colors.grayColor,
        },
        backgroundPreviewRow: {
            marginTop: 8,
            flexDirection: 'row',
            alignItems: 'center',
            justifyContent: 'space-between',
            gap: 12,
        },
        backgroundPreview: {
            flex: 1,
            height: 120,
            borderRadius: 14,
            backgroundColor: colors.btnBackgroundColor,
        },
        photoRow: {
            marginTop: 8,
        },
        photoThumbWrapper: {
            width: 92,
            height: 92,
            borderRadius: 14,
            marginRight: 10,
            backgroundColor: colors.btnBackgroundColor,
            overflow: 'hidden',
            borderWidth: 1,
            borderColor: colors.lightGrayColor,
        },
        photoThumbImage: {
            width: '100%',
            height: '100%',
        },
        photoThumbPlaceholder: {
            width: '100%',
            height: '100%',
            backgroundColor: colors.btnBackgroundColor,
        },
        mediaBadge: {
            position: 'absolute',
            right: 6,
            bottom: 6,
            backgroundColor: 'rgba(0,0,0,0.6)',
            paddingHorizontal: 6,
            paddingVertical: 2,
            borderRadius: 10,
        },
        mediaBadgeText: {
            ...Fonts.medium10,
            color: colors.pureWhite,
        },
        competitionChipsRow: {
            flexDirection: 'row',
            flexWrap: 'wrap',
            gap: 8,
            marginTop: 12,
        },
        competitionChip: {
            flexDirection: 'row',
            alignItems: 'center',
            borderWidth: 1,
            borderColor: colors.lightGrayColor,
            borderRadius: 999,
            paddingHorizontal: 12,
            paddingVertical: 6,
            backgroundColor: colors.secondaryColor,
            gap: 6,
            maxWidth: '100%',
        },
        competitionChipText: {
            ...Fonts.regular12,
            color: colors.mainTextColor,
            maxWidth: 180,
        },
        competitionChipRemove: {
            alignItems: 'center',
            justifyContent: 'center',
        },
        emptyCompetitionCard: {
            marginTop: 12,
            borderWidth: 1,
            borderColor: colors.lightGrayColor,
            borderRadius: 14,
            paddingVertical: 14,
            paddingHorizontal: 16,
            backgroundColor: colors.cardBackground,
            alignItems: 'center',
            justifyContent: 'center',
        },
        emptyCompetitionText: {
            ...Fonts.semibold14,
            color: colors.primaryColor,
        },
        actionRow: {
            flexDirection: 'row',
            gap: 12,
            marginTop: 8,
        },
        cancelButton: {
            flex: 1,
            borderWidth: 1,
            borderColor: colors.lightGrayColor,
            borderRadius: 12,
            alignItems: 'center',
            justifyContent: 'center',
            paddingVertical: 12,
        },
        cancelText: {
            ...Fonts.medium14,
            color: colors.subTextColor,
        },
        saveButton: {
            flex: 1,
            backgroundColor: colors.primaryColor,
            borderRadius: 12,
            alignItems: 'center',
            justifyContent: 'center',
            paddingVertical: 12,
        },
        saveText: {
            ...Fonts.medium14,
            color: colors.pureWhite,
        },
        deleteButton: {
            marginTop: 16,
            borderRadius: 12,
            backgroundColor: '#FFECEC',
            paddingVertical: 12,
            alignItems: 'center',
            flexDirection: 'row',
            justifyContent: 'center',
            gap: 8,
        },
        deleteText: {
            ...Fonts.medium14,
            color: '#ED5454',
        },
        modalOverlay: {
            flex: 1,
            backgroundColor: 'rgba(0,0,0,0.45)',
            justifyContent: 'center',
            paddingHorizontal: 20,
        },
        modalBackdrop: {
            position: 'absolute',
            top: 0,
            bottom: 0,
            left: 0,
            right: 0,
        },
        dateModalContainer: {
            backgroundColor: colors.cardBackground,
            borderRadius: 18,
            padding: 16,
            borderWidth: 1,
            borderColor: colors.lightGrayColor,
        },
        dateModalTitle: {
            ...Fonts.semibold16,
            color: colors.mainTextColor,
        },
        modalCard: {
            backgroundColor: colors.cardBackground,
            borderRadius: 18,
            padding: 16,
            borderWidth: 1,
            borderColor: colors.lightGrayColor,
            maxHeight: '80%',
        },
        modalHeader: {
            flexDirection: 'row',
            alignItems: 'center',
            justifyContent: 'space-between',
            marginBottom: 10,
        },
        modalTitle: {
            ...Fonts.semibold16,
            color: colors.mainTextColor,
        },
        modalCloseButton: {
            width: 34,
            height: 34,
            borderRadius: 17,
            alignItems: 'center',
            justifyContent: 'center',
            backgroundColor: colors.btnBackgroundColor,
        },
        modalSearchRow: {
            flexDirection: 'row',
            alignItems: 'center',
            borderWidth: 1,
            borderColor: colors.lightGrayColor,
            borderRadius: 12,
            backgroundColor: colors.secondaryColor,
            paddingHorizontal: 12,
            height: 46,
            marginBottom: 10,
        },
        modalSearchInput: {
            flex: 1,
            ...Fonts.regular14,
            color: colors.mainTextColor,
            marginLeft: 8,
        },
        modalList: {
            maxHeight: 360,
        },
        modalListContent: {
            paddingVertical: 4,
            gap: 8,
        },
        modalOption: {
            flexDirection: 'row',
            alignItems: 'center',
            justifyContent: 'space-between',
            borderWidth: 1,
            borderColor: colors.lightGrayColor,
            borderRadius: 14,
            paddingHorizontal: 12,
            paddingVertical: 10,
            backgroundColor: colors.secondaryColor,
        },
        modalOptionSelected: {
            borderColor: colors.primaryColor,
            backgroundColor: colors.cardBackground,
        },
        modalOptionTextWrap: {
            flex: 1,
            paddingRight: 12,
        },
        modalOptionTitle: {
            ...Fonts.medium14,
            color: colors.mainTextColor,
        },
        modalOptionSubtext: {
            ...Fonts.regular12,
            color: colors.subTextColor,
            marginTop: 2,
        },
        modalEmptyText: {
            ...Fonts.regular12,
            color: colors.subTextColor,
            textAlign: 'center',
            paddingVertical: 16,
        },
        modalDoneButton: {
            marginTop: 12,
            borderRadius: 12,
            backgroundColor: colors.primaryColor,
            paddingVertical: 12,
            alignItems: 'center',
            justifyContent: 'center',
        },
        modalDoneButtonText: {
            ...Fonts.semibold13,
            color: colors.pureWhite,
        },
        loadingOverlay: {
            position: 'absolute',
            top: 0,
            left: 0,
            right: 0,
            bottom: 0,
            backgroundColor: 'rgba(0,0,0,0.35)',
            alignItems: 'center',
            justifyContent: 'center',
            paddingHorizontal: 24,
        },
        loadingCard: {
            backgroundColor: colors.cardBackground,
            borderRadius: 14,
            paddingHorizontal: 18,
            paddingVertical: 16,
            alignItems: 'center',
            gap: 10,
            borderWidth: 1,
            borderColor: colors.lightGrayColor,
            minWidth: 180,
        },
        loadingText: {
            ...Fonts.medium14,
            color: colors.mainTextColor,
        },
    });
