import { StyleSheet } from 'react-native';
import Fonts from '../../constants/Fonts';
export const createStyles = (colors) => StyleSheet.create({
    mainContainer: {
        flex: 1,
        backgroundColor: colors.backgroundColor,
    },
    header: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 20,
        paddingVertical: 16,
        borderBottomWidth: 0.5,
        borderBottomColor: colors.lightGrayColor,
    },
    headerButton: {
        width: 44,
        height: 44,
        borderRadius: 22,
        backgroundColor: colors.btnBackgroundColor,
        alignItems: 'center',
        justifyContent: 'center',
    },
    headerTitle: Object.assign(Object.assign({}, Fonts.medium18), { color: colors.mainTextColor }),
    scrollContent: {
        paddingHorizontal: 20,
        paddingTop: 24,
    },
    fieldBlock: {
        marginBottom: 16,
    },
    stepHeaderRow: {
        marginBottom: 18,
    },
    stepCounter: Object.assign(Object.assign({}, Fonts.regular12), { color: colors.primaryColor, marginBottom: 4 }),
    stepTitle: Object.assign(Object.assign({}, Fonts.semibold16), { color: colors.mainTextColor }),
    skipRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 10,
        marginBottom: 10,
    },
    skipLabel: Object.assign(Object.assign({}, Fonts.regular13), { color: colors.mainTextColor }),
    fieldLabel: Object.assign(Object.assign({}, Fonts.regular12), { color: colors.grayColor, marginBottom: 6 }),
    sectionHeaderRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginBottom: 6,
    },
    sectionTitle: Object.assign(Object.assign({}, Fonts.semibold14), { color: colors.mainTextColor }),
    sectionAction: {
        borderWidth: 1,
        borderColor: colors.lightGrayColor,
        backgroundColor: colors.btnBackgroundColor,
        borderRadius: 999,
        paddingHorizontal: 12,
        paddingVertical: 6,
    },
    sectionActionText: Object.assign(Object.assign({}, Fonts.semibold12), { color: colors.primaryColor }),
    inlineHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginBottom: 6,
    },
    inlineAction: {
        paddingHorizontal: 10,
        paddingVertical: 6,
        borderRadius: 10,
        backgroundColor: colors.btnBackgroundColor,
    },
    inlineActionText: Object.assign(Object.assign({}, Fonts.medium12), { color: colors.primaryColor }),
    dateButton: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
        borderWidth: 1,
        borderColor: colors.lightGrayColor,
        borderRadius: 12,
        paddingHorizontal: 12,
        paddingVertical: 12,
        backgroundColor: colors.btnBackgroundColor,
    },
    dateText: Object.assign(Object.assign({}, Fonts.regular14), { color: colors.mainTextColor }),
    fieldInput: Object.assign(Object.assign({ borderWidth: 1, borderColor: colors.lightGrayColor, borderRadius: 12, paddingHorizontal: 14, paddingVertical: 15, minHeight: 54 }, Fonts.regular15), { color: colors.mainTextColor, backgroundColor: colors.btnBackgroundColor }),
    fieldTextarea: {
        minHeight: 150,
        textAlignVertical: 'top',
    },
    helperText: Object.assign(Object.assign({}, Fonts.regular12), { color: colors.grayColor }),
    backgroundPreviewRow: {
        marginTop: 8,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        gap: 12,
    },
    backgroundPreview: {
        flex: 1,
        height: 120,
        borderRadius: 14,
        backgroundColor: colors.btnBackgroundColor,
    },
    photoRow: {
        marginTop: 8,
    },
    photoThumbWrapper: {
        width: 92,
        height: 92,
        borderRadius: 14,
        marginRight: 10,
        backgroundColor: colors.btnBackgroundColor,
        overflow: 'hidden',
        borderWidth: 1,
        borderColor: colors.lightGrayColor,
    },
    photoThumbImage: {
        width: '100%',
        height: '100%',
    },
    photoThumbPlaceholder: {
        width: '100%',
        height: '100%',
        backgroundColor: colors.btnBackgroundColor,
    },
    mediaBadge: {
        position: 'absolute',
        right: 6,
        bottom: 6,
        backgroundColor: 'rgba(0,0,0,0.6)',
        paddingHorizontal: 6,
        paddingVertical: 2,
        borderRadius: 10,
    },
    mediaBadgeText: Object.assign(Object.assign({}, Fonts.medium10), { color: colors.pureWhite }),
    competitionChipsRow: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 8,
        marginTop: 12,
    },
    competitionChip: {
        flexDirection: 'row',
        alignItems: 'center',
        borderWidth: 1,
        borderColor: colors.lightGrayColor,
        borderRadius: 999,
        paddingHorizontal: 12,
        paddingVertical: 6,
        backgroundColor: colors.secondaryColor,
        gap: 6,
        maxWidth: '100%',
    },
    competitionChipText: Object.assign(Object.assign({}, Fonts.regular12), { color: colors.mainTextColor, maxWidth: 180 }),
    competitionChipRemove: {
        alignItems: 'center',
        justifyContent: 'center',
    },
    emptyCompetitionCard: {
        marginTop: 12,
        borderWidth: 1,
        borderColor: colors.lightGrayColor,
        borderRadius: 14,
        paddingVertical: 14,
        paddingHorizontal: 16,
        backgroundColor: colors.cardBackground,
        alignItems: 'center',
        justifyContent: 'center',
    },
    emptyCompetitionText: Object.assign(Object.assign({}, Fonts.semibold14), { color: colors.primaryColor }),
    actionRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 12,
        marginTop: 8,
    },
    previewShortcutButton: {
        minWidth: 94,
        borderWidth: 1,
        borderColor: colors.primaryColor,
        borderRadius: 12,
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 12,
        paddingHorizontal: 12,
        backgroundColor: colors.cardBackground,
    },
    previewShortcutText: Object.assign(Object.assign({}, Fonts.medium13), { color: colors.primaryColor }),
    cancelButton: {
        flex: 1,
        borderWidth: 1,
        borderColor: colors.lightGrayColor,
        borderRadius: 12,
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 12,
    },
    cancelText: Object.assign(Object.assign({}, Fonts.medium14), { color: colors.subTextColor }),
    saveButton: {
        flex: 1,
        backgroundColor: colors.primaryColor,
        borderRadius: 12,
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 12,
    },
    saveText: Object.assign(Object.assign({}, Fonts.medium14), { color: colors.pureWhite }),
    deleteButton: {
        marginTop: 16,
        borderRadius: 12,
        backgroundColor: '#FFECEC',
        paddingVertical: 12,
        alignItems: 'center',
        flexDirection: 'row',
        justifyContent: 'center',
        gap: 8,
    },
    deleteText: Object.assign(Object.assign({}, Fonts.medium14), { color: '#ED5454' }),
    previewCard: {
        borderWidth: 1,
        borderColor: colors.lightGrayColor,
        borderRadius: 14,
        padding: 14,
        backgroundColor: colors.cardBackground,
        gap: 8,
    },
    previewTitle: Object.assign(Object.assign({}, Fonts.semibold16), { color: colors.mainTextColor }),
    previewMeta: Object.assign(Object.assign({}, Fonts.regular12), { color: colors.subTextColor }),
    previewText: Object.assign(Object.assign({}, Fonts.regular14), { color: colors.mainTextColor }),
    previewSubline: Object.assign(Object.assign({}, Fonts.regular13), { color: colors.mainTextColor }),
    modalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0,0,0,0.45)',
        justifyContent: 'center',
        paddingHorizontal: 20,
    },
    modalBackdrop: {
        position: 'absolute',
        top: 0,
        bottom: 0,
        left: 0,
        right: 0,
    },
    dateModalContainer: {
        backgroundColor: colors.cardBackground,
        borderRadius: 18,
        padding: 16,
        borderWidth: 1,
        borderColor: colors.lightGrayColor,
    },
    dateModalTitle: Object.assign(Object.assign({}, Fonts.semibold16), { color: colors.mainTextColor }),
    modalCard: {
        backgroundColor: colors.cardBackground,
        borderRadius: 18,
        padding: 16,
        borderWidth: 1,
        borderColor: colors.lightGrayColor,
        maxHeight: '80%',
    },
    modalHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginBottom: 10,
    },
    modalTitle: Object.assign(Object.assign({}, Fonts.semibold16), { color: colors.mainTextColor }),
    modalCloseButton: {
        width: 34,
        height: 34,
        borderRadius: 17,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: colors.btnBackgroundColor,
    },
    modalSearchRow: {
        flexDirection: 'row',
        alignItems: 'center',
        borderWidth: 1,
        borderColor: colors.lightGrayColor,
        borderRadius: 12,
        backgroundColor: colors.secondaryColor,
        paddingHorizontal: 12,
        height: 46,
        marginBottom: 10,
    },
    modalSearchInput: Object.assign(Object.assign({ flex: 1 }, Fonts.regular14), { color: colors.mainTextColor, marginLeft: 8 }),
    modalList: {
        maxHeight: 360,
    },
    modalListContent: {
        paddingVertical: 4,
        gap: 8,
    },
    modalOption: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        borderWidth: 1,
        borderColor: colors.lightGrayColor,
        borderRadius: 14,
        paddingHorizontal: 12,
        paddingVertical: 10,
        backgroundColor: colors.secondaryColor,
    },
    modalOptionSelected: {
        borderColor: colors.primaryColor,
        backgroundColor: colors.cardBackground,
    },
    modalOptionTextWrap: {
        flex: 1,
        paddingRight: 12,
    },
    modalOptionTitle: Object.assign(Object.assign({}, Fonts.medium14), { color: colors.mainTextColor }),
    modalOptionSubtext: Object.assign(Object.assign({}, Fonts.regular12), { color: colors.subTextColor, marginTop: 2 }),
    modalEmptyText: Object.assign(Object.assign({}, Fonts.regular12), { color: colors.subTextColor, textAlign: 'center', paddingVertical: 16 }),
    modalDoneButton: {
        marginTop: 12,
        borderRadius: 12,
        backgroundColor: colors.primaryColor,
        paddingVertical: 12,
        alignItems: 'center',
        justifyContent: 'center',
    },
    modalDoneButtonText: Object.assign(Object.assign({}, Fonts.semibold13), { color: colors.pureWhite }),
    loadingOverlay: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        backgroundColor: 'rgba(0,0,0,0.35)',
        alignItems: 'center',
        justifyContent: 'center',
        paddingHorizontal: 24,
    },
    loadingCard: {
        backgroundColor: colors.cardBackground,
        borderRadius: 14,
        paddingHorizontal: 18,
        paddingVertical: 16,
        alignItems: 'center',
        gap: 10,
        borderWidth: 1,
        borderColor: colors.lightGrayColor,
        minWidth: 180,
    },
    loadingText: Object.assign(Object.assign({}, Fonts.medium14), { color: colors.mainTextColor }),
});
