import { StyleSheet, Dimensions } from 'react-native';
import Fonts from '../../constants/Fonts';
import { ThemeColors, lightColors } from '../../constants/Theme';

const { width, height } = Dimensions.get('window');

export const createStyles = (colors: ThemeColors) => StyleSheet.create({
    mainContainer: {
        flex: 1,
        backgroundColor: colors.backgroundColor,
    },
    header: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 20,
        paddingVertical: 16,
        borderBottomWidth: 0.5,
        borderBottomColor: colors.borderColor,
    },
    headerLeft: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 12,
    },
    calendarIconContainer: {
        width: 40,
        height: 40,
        borderRadius: 90,
        backgroundColor: colors.primaryColor,
        alignItems: 'center',
        justifyContent: 'center',
    },
    headerTitleContainer: {
        width: 168,
    },
    headerTitle: {
        ...Fonts.medium16,
        color: colors.mainTextColor,
        textAlign: 'center',
    },
    headerSubtitle: {
        ...Fonts.regular12,
        color: colors.mainTextColor,
    },
    // Question Card
    questionCard: {
        marginHorizontal: 20,
        marginTop: 16,
        backgroundColor: colors.cardBackground,
        borderRadius: 10,
        borderWidth: 0.5,
        borderColor: colors.borderColor,
        paddingHorizontal: 16,
        paddingVertical: 12,
        alignItems: 'center',
    },
    questionText: {
        ...Fonts.regular14,
        color: colors.subTextColor,
        textAlign: 'center',
        marginBottom: 12,
    },
    buttonsRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 12,
    },
    noButton: {
        backgroundColor: '#ED5454',
        borderRadius: 8,
        paddingHorizontal: 13,
        paddingVertical: 8,
        width: 112,
        alignItems: 'center',
        justifyContent: 'center',
    },
    yesButton: {
        backgroundColor: colors.primaryColor,
        borderRadius: 8,
        paddingHorizontal: 13,
        paddingVertical: 8,
        width: 112,
        alignItems: 'center',
        justifyContent: 'center',
    },
    buttonText: {
        fontSize: 11,
        fontFamily: 'Inter-Regular',
        color: colors.pureWhite,
        lineHeight: 17,
    },
    // Video Container
    videoContainer: {
        flex: 1,
        marginTop: 16,
        position: 'relative',
    },
    videoImage: {
        width: '100%',
        height: '100%',
    },
    // Side Actions
    sideActions: {
        position: 'absolute',
        right: 20,
        top: '40%',
        gap: 12,
    },
    actionButton: {
        width: 50,
        height: 50,
        borderRadius: 90,
        backgroundColor: colors.secondaryColor,
        alignItems: 'center',
        justifyContent: 'center',
    },
    // Video Controls
    controlsContainer: {
        position: 'absolute',
        bottom: 40,
        left: 0,
        right: 0,
        alignItems: 'center',
        gap: 24,
    },
    progressBarContainer: {
        width: width - 40,
        height: 18,
        justifyContent: 'center',
    },
    progressBarBackground: {
        width: '100%',
        height: 4,
        backgroundColor: 'rgba(255, 255, 255, 0.5)',
        borderRadius: 2,
    },
    progressBarFill: {
        width: '30%',
        height: '100%',
        backgroundColor: colors.primaryColor,
        borderRadius: 2,
    },
    progressThumb: {
        position: 'absolute',
        left: '30%',
        width: 12,
        height: 12,
        borderRadius: 6,
        backgroundColor: colors.primaryColor,
        marginLeft: -6,
    },
    controlButtons: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 28,
    },
    skipButton: {
        width: 50,
        height: 50,
        borderRadius: 25,
        backgroundColor: colors.borderColor,
        alignItems: 'center',
        justifyContent: 'center',
    },
    playButton: {
        width: 80,
        height: 80,
        borderRadius: 40,
        backgroundColor: 'rgba(0, 0, 0, 0.25)',
        alignItems: 'center',
        justifyContent: 'center',
    },
    // Buy Modal Styles
    modalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0,0,0,0.5)',
        justifyContent: 'center',
        alignItems: 'center',
    },
    modalContainer: {
        width: 310,
        backgroundColor: colors.modalBackground,
        borderRadius: 8,
        borderWidth: 0.4,
        borderColor: colors.borderColor,
        paddingHorizontal: 13,
        paddingVertical: 16,
        alignItems: 'center',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 0 },
        shadowOpacity: 0.25,
        shadowRadius: 119,
        elevation: 10,
    },
    modalImage: {
        width: 276,
        height: 276,
        borderRadius: 8,
    },
    modalInfoRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        width: 259,
        marginTop: 13,
    },
    modalTitle: {
        ...Fonts.medium14,
        color: colors.mainTextColor,
    },
    modalPrice: {
        ...Fonts.medium14,
        color: colors.mainTextColor,
    },
    modalDivider: {
        width: '100%',
        height: 0.4,
        backgroundColor: colors.borderColor,
        marginVertical: 16,
    },
    modalButtonsRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 13,
    },
    cancelButton: {
        backgroundColor: '#ED5454',
        borderRadius: 8,
        paddingHorizontal: 13,
        paddingVertical: 8,
        width: 112,
        alignItems: 'center',
        justifyContent: 'center',
    },
    payButton: {
        backgroundColor: colors.primaryColor,
        borderRadius: 8,
        paddingHorizontal: 13,
        paddingVertical: 8,
        width: 112,
        alignItems: 'center',
        justifyContent: 'center',
    },
    modalButtonText: {
        fontSize: 11,
        fontFamily: 'Inter-Regular',
        color: colors.pureWhite,
        lineHeight: 17,
    },
    // Success Modal Styles
    successModalContainer: {
        width: 297,
        backgroundColor: colors.modalBackground,
        borderRadius: 10,
        borderWidth: 0.5,
        borderColor: colors.borderColor,
        paddingHorizontal: 16,
        paddingVertical: 20,
        alignItems: 'center',
        justifyContent: 'space-between',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 0 },
        shadowOpacity: 0.25,
        shadowRadius: 152,
        elevation: 10,
    },
    successIconContainer: {
        alignItems: 'center',
        justifyContent: 'center',
    },
    successTitle: {
        ...Fonts.medium16,
        color: colors.mainTextColor,
        textAlign: 'center',
        marginTop: 5,
    },
    successSubtitle: {
        fontSize: 10,
        fontFamily: 'Inter-Regular',
        color: colors.subTextColor,
        textAlign: 'center',
        lineHeight: 15,
    },
    downloadButton: {
        backgroundColor: colors.primaryColor,
        borderRadius: 10,
        paddingHorizontal: 13,
        paddingVertical: 13,
        width: 269,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 6,
        marginTop: 16,
    },
    downloadButtonText: {
        ...Fonts.medium14,
        color: colors.pureWhite,
        fontSize: 13,
    },
    // Failed Modal Styles
    failedModalContainer: {
        width: 297,
        backgroundColor: colors.modalBackground,
        borderRadius: 10,
        borderWidth: 0.5,
        borderColor: colors.borderColor,
        paddingHorizontal: 16,
        paddingVertical: 20,
        alignItems: 'center',
        justifyContent: 'space-between',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 0 },
        shadowOpacity: 0.25,
        shadowRadius: 152,
        elevation: 10,
    },
    failedIconContainer: {
        alignItems: 'center',
        justifyContent: 'center',
    },
    failedTitle: {
        ...Fonts.medium16,
        color: colors.mainTextColor,
        textAlign: 'center',
        marginTop: 5,
    },
    failedSubtitle: {
        fontSize: 10,
        fontFamily: 'Inter-Regular',
        color: colors.subTextColor,
        textAlign: 'center',
        lineHeight: 15,
    },
    failedButtonsRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 16,
        width: '100%',
        marginTop: 16,
    },
    failedCancelButton: {
        backgroundColor: '#ED5454',
        borderRadius: 6,
        paddingHorizontal: 16,
        paddingVertical: 10,
        width: 116,
        alignItems: 'center',
        justifyContent: 'center',
    },
    rechargeButton: {
        backgroundColor: colors.primaryColor,
        borderRadius: 6,
        paddingHorizontal: 16,
        paddingVertical: 10,
        width: 115,
        alignItems: 'center',
        justifyContent: 'center',
    },
    failedButtonText: {
        ...Fonts.regular14,
        color: colors.pureWhite,
    },
});

// Backward compatibility
const Styles = createStyles(lightColors);
export default Styles;
