import { StyleSheet, Dimensions } from 'react-native';
import Fonts from '../../constants/Fonts';
import { ThemeColors, lightColors } from '../../constants/Theme';

const { width, height } = Dimensions.get('window');

export const createStyles = (colors: ThemeColors) => StyleSheet.create({
    mainContainer: {
        flex: 1,
        backgroundColor: colors.backgroundColor,
    },
    header: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 20,
        paddingVertical: 16,
        borderBottomWidth: 0.5,
        borderBottomColor: colors.borderColor,
    },
    headerBack: {
        width: 40,
        height: 40,
        borderRadius: 20,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: colors.btnBackgroundColor,
    },
    headerMore: {
        width: 40,
        height: 40,
        borderRadius: 20,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: 'transparent',
    },
    headerTitleCentered: {
        ...Fonts.medium16,
        color: colors.mainTextColor,
        flex: 1,
        textAlign: 'center',
        marginHorizontal: 10,
    },
    // Video Container
    videoContainer: {
        flex: 1,
        marginTop: 0,
        position: 'relative',
    },
    videoImage: {
        width: '100%',
        height: '100%',
    },
    playButtonOverlay: {
        position: 'absolute',
        top: '50%',
        left: '50%',
        marginTop: -28,
        marginLeft: -28,
        width: 56,
        height: 56,
        borderRadius: 28,
        backgroundColor: 'rgba(0,0,0,0.25)',
        alignItems: 'center',
        justifyContent: 'center',
    },
    progressContainer: {
        paddingHorizontal: 16,
        paddingTop: 6,
        paddingBottom: 4,
    },
    videoSliderOverlay: {
        position: 'absolute',
        left: 12,
        right: 12,
        bottom: 12,
        paddingVertical: 6,
        paddingHorizontal: 6,
        borderRadius: 12,
        backgroundColor: 'transparent',
    },
    videoSliderLabelRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginBottom: 6,
    },
    videoSliderTimeBubble: {
        position: 'absolute',
        top: -20,
        minWidth: 32,
        paddingHorizontal: 6,
        paddingVertical: 2,
        borderRadius: 8,
        backgroundColor: 'rgba(0,0,0,0.55)',
        alignItems: 'center',
    },
    videoSliderTime: {
        ...Fonts.medium12,
        color: '#FFFFFF',
    },
    menuOverlay: {
        flex: 1,
        backgroundColor: 'transparent',
        justifyContent: 'flex-start',
        alignItems: 'flex-end',
        paddingTop: 90,
        paddingHorizontal: 16,
    },
    menuCard: {
        backgroundColor: colors.cardBackground,
        borderRadius: 12,
        paddingVertical: 10,
        paddingHorizontal: 8,
        alignSelf: 'flex-end',
        width: 180,
        borderWidth: 0.5,
        borderColor: colors.borderColor,
    },
    menuAction: {
        paddingVertical: 10,
        paddingHorizontal: 12,
        borderRadius: 8,
    },
    menuActionText: {
        ...Fonts.medium14,
        color: colors.mainTextColor,
    },
    moreMenuOverlay: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        paddingHorizontal: 20,
    },
    moreMenuBackdrop: {
        position: 'absolute',
        top: 0,
        bottom: 0,
        left: 0,
        right: 0,
        backgroundColor: 'rgba(0,0,0,0.45)',
    },
    moreMenuContainer: {
        width: '100%',
        maxWidth: 420,
        backgroundColor: colors.modalBackground,
        borderRadius: 16,
        borderWidth: 0.5,
        borderColor: colors.lightGrayColor,
        padding: 14,
    },
    moreMenuTitle: {
        ...Fonts.medium16,
        color: colors.mainTextColor,
        marginBottom: 8,
    },
    moreMenuDivider: {
        height: 1,
        backgroundColor: colors.lightGrayColor,
        marginBottom: 8,
    },
    moreMenuAction: {
        backgroundColor: colors.secondaryColor,
        borderRadius: 10,
        paddingHorizontal: 12,
        paddingVertical: 12,
        marginBottom: 8,
    },
    moreMenuActionText: {
        ...Fonts.regular14,
        color: colors.mainTextColor,
    },
    moreMenuCancel: {
        marginTop: 4,
        borderWidth: 1,
        borderColor: colors.lightGrayColor,
        borderRadius: 10,
        paddingHorizontal: 12,
        paddingVertical: 12,
        alignItems: 'center',
        backgroundColor: colors.btnBackgroundColor,
    },
    moreMenuCancelText: {
        ...Fonts.medium14,
        color: colors.grayColor,
    },
    infoModalContainer: {
        width: '100%',
        maxWidth: 420,
        backgroundColor: colors.modalBackground,
        borderRadius: 16,
        borderWidth: 0.5,
        borderColor: colors.lightGrayColor,
        padding: 16,
        gap: 10,
    },
    infoModalTitle: {
        ...Fonts.medium16,
        color: colors.mainTextColor,
    },
    infoModalText: {
        ...Fonts.regular14,
        color: colors.subTextColor,
    },
    infoModalSubmitButton: {
        alignSelf: 'stretch',
        alignItems: 'center',
        backgroundColor: colors.primaryColor,
        borderRadius: 10,
        paddingHorizontal: 16,
        paddingVertical: 12,
    },
    infoModalSubmitButtonText: {
        ...Fonts.medium14,
        color: colors.pureWhite,
    },
    // Buy Modal Styles
    modalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0,0,0,0.5)',
        justifyContent: 'center',
        alignItems: 'center',
    },
    modalContainer: {
        width: 310,
        backgroundColor: colors.modalBackground,
        borderRadius: 8,
        borderWidth: 0.4,
        borderColor: colors.borderColor,
        paddingHorizontal: 13,
        paddingVertical: 16,
        alignItems: 'center',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 0 },
        shadowOpacity: 0.25,
        shadowRadius: 119,
        elevation: 10,
    },
    modalImage: {
        width: 276,
        height: 276,
        borderRadius: 8,
    },
    modalInfoRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        width: 259,
        marginTop: 13,
    },
    modalTitle: {
        ...Fonts.medium14,
        color: colors.mainTextColor,
    },
    modalPrice: {
        ...Fonts.medium14,
        color: colors.mainTextColor,
    },
    modalDivider: {
        width: '100%',
        height: 0.4,
        backgroundColor: colors.borderColor,
        marginVertical: 16,
    },
    modalButtonsRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 13,
    },
    cancelButton: {
        backgroundColor: '#ED5454',
        borderRadius: 8,
        paddingHorizontal: 13,
        paddingVertical: 8,
        width: 112,
        alignItems: 'center',
        justifyContent: 'center',
    },
    payButton: {
        backgroundColor: colors.primaryColor,
        borderRadius: 8,
        paddingHorizontal: 13,
        paddingVertical: 8,
        width: 112,
        alignItems: 'center',
        justifyContent: 'center',
    },
    modalButtonText: {
        fontSize: 11,
        fontFamily: 'Inter-Regular',
        color: colors.pureWhite,
        lineHeight: 17,
    },
    // Success Modal Styles
    successModalContainer: {
        width: 297,
        backgroundColor: colors.modalBackground,
        borderRadius: 10,
        borderWidth: 0.5,
        borderColor: colors.borderColor,
        paddingHorizontal: 16,
        paddingVertical: 20,
        alignItems: 'center',
        justifyContent: 'space-between',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 0 },
        shadowOpacity: 0.25,
        shadowRadius: 152,
        elevation: 10,
    },
    successIconContainer: {
        alignItems: 'center',
        justifyContent: 'center',
    },
    successTitle: {
        ...Fonts.medium16,
        color: colors.mainTextColor,
        textAlign: 'center',
        marginTop: 5,
    },
    successSubtitle: {
        fontSize: 10,
        fontFamily: 'Inter-Regular',
        color: colors.subTextColor,
        textAlign: 'center',
        lineHeight: 15,
    },
    downloadButton: {
        backgroundColor: colors.primaryColor,
        borderRadius: 10,
        paddingHorizontal: 13,
        paddingVertical: 13,
        width: 269,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 6,
        marginTop: 16,
    },
    downloadButtonText: {
        ...Fonts.medium14,
        color: colors.pureWhite,
        fontSize: 13,
    },
    // Failed Modal Styles
    failedModalContainer: {
        width: 297,
        backgroundColor: colors.modalBackground,
        borderRadius: 10,
        borderWidth: 0.5,
        borderColor: colors.borderColor,
        paddingHorizontal: 16,
        paddingVertical: 20,
        alignItems: 'center',
        justifyContent: 'space-between',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 0 },
        shadowOpacity: 0.25,
        shadowRadius: 152,
        elevation: 10,
    },
    failedIconContainer: {
        alignItems: 'center',
        justifyContent: 'center',
    },
    failedTitle: {
        ...Fonts.medium16,
        color: colors.mainTextColor,
        textAlign: 'center',
        marginTop: 5,
    },
    failedSubtitle: {
        fontSize: 10,
        fontFamily: 'Inter-Regular',
        color: colors.subTextColor,
        textAlign: 'center',
        lineHeight: 15,
    },
    failedButtonsRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 16,
        width: '100%',
        marginTop: 16,
    },
    failedCancelButton: {
        backgroundColor: '#ED5454',
        borderRadius: 6,
        paddingHorizontal: 16,
        paddingVertical: 10,
        width: 116,
        alignItems: 'center',
        justifyContent: 'center',
    },
    rechargeButton: {
        backgroundColor: colors.primaryColor,
        borderRadius: 6,
        paddingHorizontal: 16,
        paddingVertical: 10,
        width: 115,
        alignItems: 'center',
        justifyContent: 'center',
    },
    failedButtonText: {
        ...Fonts.regular14,
        color: colors.pureWhite,
    },
});

// Backward compatibility
const Styles = createStyles(lightColors);
export default Styles;
