import {StyleSheet} from 'react-native';
import Fonts from '../../constants/Fonts';
import type {ThemeColors} from '../../constants/Theme';

export const createStyles = (colors: ThemeColors) =>
  StyleSheet.create({
    mainContainer: {
      flex: 1,
      backgroundColor: colors.backgroundColor,
    },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: 20,
      paddingVertical: 15,
      borderBottomWidth: 0.5,
      borderBottomColor: colors.lightGrayColor,
    },
    backButton: {
      width: 44,
      height: 44,
      borderRadius: 22,
      backgroundColor: colors.btnBackgroundColor,
      alignItems: 'center',
      justifyContent: 'center',
    },
    headerTitle: {
      ...Fonts.medium16,
      fontSize: 18,
      color: colors.mainTextColor,
    },
    notificationButton: {
      width: 44,
      height: 44,
      borderRadius: 22,
      backgroundColor: colors.btnBackgroundColor,
      alignItems: 'center',
      justifyContent: 'center',
    },
    scrollContent: {
      paddingHorizontal: 20,
      paddingTop: 20,
      paddingBottom: 100,
    },
    filterRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 8,
      marginBottom: 16,
    },
    searchRow: {
      marginBottom: 16,
    },
    searchField: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      borderWidth: 1,
      borderColor: colors.lightGrayColor,
      backgroundColor: colors.btnBackgroundColor,
      borderRadius: 12,
      paddingHorizontal: 12,
      height: 44,
    },
    searchInput: {
      flex: 1,
      ...Fonts.regular14,
      color: colors.mainTextColor,
      paddingVertical: 0,
    },
    filterChip: {
      paddingHorizontal: 12,
      paddingVertical: 6,
      borderRadius: 6,
      backgroundColor: colors.btnBackgroundColor,
    },
    filterChipActive: {
      backgroundColor: colors.primaryColor,
    },
    filterChipText: {
      ...Fonts.regular12,
      color: colors.grayColor,
    },
    filterChipTextActive: {
      color: colors.pureWhite,
    },
    sectionBlock: {
      marginBottom: 12,
    },
    sectionHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 16,
    },
    sectionTitle: {
      ...Fonts.medium16,
      fontSize: 18,
      color: colors.mainTextColor,
    },
    sectionSubtitle: {
      ...Fonts.regular14,
      color: colors.grayColor,
      marginTop: 4,
    },
    viewAllText: {
      ...Fonts.regular14,
      color: colors.grayColor,
    },

    // Shared card styles
    appearanceCard: {
      backgroundColor: colors.cardBackground,
      borderWidth: 0.5,
      borderColor: colors.lightGrayColor,
      borderRadius: 10,
      padding: 16,
      marginBottom: 16,
    },
    hubCard: {
      backgroundColor: colors.cardBackground,
      borderWidth: 0.5,
      borderColor: colors.lightGrayColor,
      borderRadius: 10,
      padding: 16,
      marginBottom: 16,
    },
    hubCardRow: {
      flexDirection: 'row',
    },
    cardHeaderRow: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      justifyContent: 'space-between',
      gap: 8,
      flexWrap: 'wrap',
    },
    typeBadge: {
      backgroundColor: colors.btnBackgroundColor,
      paddingHorizontal: 10,
      paddingVertical: 4,
      borderRadius: 6,
      alignSelf: 'flex-start',
    },
    typeBadgeText: {
      ...Fonts.regular12,
      color: colors.subTextColor,
    },
    myEventCard: {
      backgroundColor: colors.cardBackground,
      borderWidth: 0.5,
      borderColor: colors.lightGrayColor,
      borderRadius: 10,
      padding: 16,
      marginBottom: 16,
      flexDirection: 'row',
    },
    cardRow: {
      flexDirection: 'row',
    },
    squareThumbnail: {
      width: 86,
      height: 86,
      borderRadius: 10,
    },
    squareThumbnailPlaceholder: {
      width: 86,
      height: 86,
      borderRadius: 10,
      backgroundColor: colors.cardBackground,
      borderWidth: 0.5,
      borderColor: colors.lightGrayColor,
    },
    cardInfo: {
      flex: 1,
      marginLeft: 12,
    },
    titleRow: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 6,
    },
    playIconCircle: {
      width: 20,
      height: 20,
      borderRadius: 12,
      backgroundColor: colors.primaryColor,
      alignItems: 'center',
      justifyContent: 'center',
      marginRight: 6,
    },
    cardTitle: {
      ...Fonts.medium14,
      color: colors.mainTextColor,
      flex: 1,
      minWidth: 0,
      flexShrink: 1,
    },
    cardSubtitle: {
      ...Fonts.regular12,
      color: colors.grayColor,
      marginTop: 4,
      marginBottom: 6,
    },
    eventTitleRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: 6,
    },
    videosCount: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
    },
    detailRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: 6,
    },
    detailLabel: {
      ...Fonts.regular12,
      color: colors.grayColor,
    },
    detailValue: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
      flexWrap: 'nowrap',
    },
    detailDot: {
      width: 4,
      height: 4,
      borderRadius: 2,
      backgroundColor: colors.grayColor,
      marginHorizontal: 6,
    },
    detailText: {
      ...Fonts.regular12,
      color: colors.grayColor,
    },
    detailTextTruncate: {
      flexShrink: 1,
      minWidth: 0,
    },
    matchBadge: {
      alignSelf: 'flex-start',
      backgroundColor: colors.btnBackgroundColor,
      borderRadius: 12,
      paddingHorizontal: 10,
      paddingVertical: 4,
      marginTop: 8,
    },
    matchBadgeText: {
      ...Fonts.regular12,
      color: colors.mainTextColor,
    },
    statusBadge: {
      paddingHorizontal: 10,
      paddingVertical: 4,
      borderRadius: 12,
    },
    statusActive: {
      backgroundColor: colors.primaryColor,
    },
    statusDone: {
      backgroundColor: '#EAF7EF',
    },
    statusText: {
      ...Fonts.regular12,
      color: colors.mainTextColor,
    },
    statusTextActive: {
      color: colors.pureWhite,
    },
    divider: {
      height: 0.5,
      backgroundColor: colors.lightGrayColor,
      marginVertical: 12,
    },
    viewButton: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: colors.primaryColor,
      borderRadius: 8,
      paddingHorizontal: 16,
      paddingVertical: 10,
      alignSelf: 'flex-start',
      height: 36,
    },
    viewButtonText: {
      ...Fonts.regular14,
      color: colors.pureWhite,
      marginRight: 6,
    },

    // Primary Button
    primaryButton: {
      backgroundColor: colors.primaryColor,
      borderRadius: 10,
      height: 54,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: 16,
    },
    primaryButtonText: {
      ...Fonts.medium16,
      color: colors.pureWhite,
      marginRight: 8,
    },

    // Downloads Section
    downloadsCard: {
      backgroundColor: colors.cardBackground,
      borderWidth: 0.5,
      borderColor: colors.lightGrayColor,
      borderRadius: 10,
      padding: 16,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: 16,
    },
    downloadsInfo: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    downloadsText: {
      ...Fonts.regular14,
      color: colors.mainTextColor,
      marginLeft: 10,
    },
    downloadsNumber: {
      fontSize: 14,
      fontWeight: '700',
      color: colors.mainTextColor,
      marginLeft: 6,
    },
    detailsButton: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: colors.cardBackground,
      borderWidth: 1,
      borderColor: colors.lightGrayColor,
      borderRadius: 6,
      paddingHorizontal: 12,
      paddingVertical: 8,
    },
    detailsButtonText: {
      ...Fonts.regular14,
      color: colors.subTextColor,
      marginRight: 4,
    },

    // Created Events Card with Badge
    createdEventCard: {
      backgroundColor: colors.cardBackground,
      borderWidth: 0.5,
      borderColor: colors.lightGrayColor,
      borderRadius: 10,
      overflow: 'hidden',
      marginBottom: 16,
    },
    requestBadge: {
      backgroundColor: '#FFF7E3',
      paddingHorizontal: 12,
      paddingVertical: 8,
      flexDirection: 'row',
      alignItems: 'center',
    },
    requestBadgeSmall: {
      backgroundColor: '#FFF7E3',
      paddingHorizontal: 6,
      paddingVertical: 6,
      borderRadius: 6,
      flexDirection: 'row',
      alignItems: 'center',
      alignSelf: 'flex-start',
      marginBottom: 8,
    },
    requestBadgeText: {
      ...Fonts.regular12,
      color: colors.grayColor,
      marginLeft: 4,
    },
    createdEventContent: {
      padding: 16,
      flexDirection: 'row',
    },

    // Video Card - Horizontal layout
    videoCard: {
      backgroundColor: colors.cardBackground,
      borderWidth: 0.5,
      borderColor: colors.lightGrayColor,
      borderRadius: 10,
      padding: 16,
      flexDirection: 'row',
      marginBottom: 16,
    },
    videoThumbnailWrapper: {
      width: 109,
      height: 140,
      borderRadius: 6,
      overflow: 'hidden',
      position: 'relative',
    },
    videoThumbnail: {
      width: '100%',
      height: '100%',
    },
    videoPlayButton: {
      position: 'absolute',
      top: '50%',
      left: '50%',
      marginTop: -20,
      marginLeft: -20,
      width: 40,
      height: 40,
      borderRadius: 20,
      backgroundColor: 'rgba(0,0,0,0.25)',
      alignItems: 'center',
      justifyContent: 'center',
    },
    videoInfo: {
      flex: 1,
      marginLeft: 12,
    },
    videoTitle: {
      ...Fonts.medium14,
      color: colors.mainTextColor,
      marginBottom: 8,
    },
    videoMeta: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 12,
    },
    videoMetaItem: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
    },
    videoMetaDot: {
      width: 6,
      height: 6,
      borderRadius: 3,
      backgroundColor: colors.grayColor,
      marginHorizontal: 8,
    },
    downloadButton: {
      backgroundColor: colors.primaryColor,
      borderRadius: 8,
      paddingHorizontal: 16,
      paddingVertical: 10,
      flexDirection: 'row',
      alignItems: 'center',
      alignSelf: 'flex-start',
      height: 38,
    },
    downloadButtonText: {
      ...Fonts.regular14,
      color: colors.pureWhite,
      marginRight: 6,
    },
    feedbackButton: {
      marginTop: 12,
      flexDirection: 'row',
      alignItems: 'center',
      alignSelf: 'flex-start',
      gap: 6,
    },
    feedbackButtonText: {
      ...Fonts.medium14,
      color: colors.primaryColor,
    },
    loadMoreButton: {
      height: 44,
      borderRadius: 10,
      borderWidth: 0.5,
      borderColor: colors.lightGrayColor,
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: 24,
    },
    loadMoreText: {
      ...Fonts.medium14,
      color: colors.mainTextColor,
    },
    infoBackdrop: {
      flex: 1,
      backgroundColor: 'rgba(0,0,0,0.4)',
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: 20,
    },
    infoCard: {
      width: '100%',
      backgroundColor: colors.whiteColor,
      borderRadius: 16,
      padding: 16,
    },
    infoTitle: {
      ...Fonts.medium18,
      color: colors.mainTextColor,
    },
    infoText: {
      ...Fonts.regular14,
      color: colors.grayColor,
      marginTop: 8,
    },
    infoCheckRow: {
      flexDirection: 'row',
      alignItems: 'center',
      marginTop: 14,
      gap: 8,
    },
    infoCheckBox: {
      width: 18,
      height: 18,
      borderRadius: 5,
      borderWidth: 1,
      borderColor: colors.lightGrayColor,
      alignItems: 'center',
      justifyContent: 'center',
    },
    infoCheckBoxActive: {
      backgroundColor: colors.primaryColor,
      borderColor: colors.primaryColor,
    },
    infoCheckMark: {
      color: colors.pureWhite,
      fontSize: 12,
      fontWeight: '700',
    },
    infoCheckText: {
      ...Fonts.regular12,
      color: colors.grayColor,
    },
    infoButtonsRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      marginTop: 16,
    },
    infoCancelButton: {
      flex: 1,
      height: 46,
      borderRadius: 10,
      borderWidth: 0.5,
      borderColor: colors.lightGrayColor,
      alignItems: 'center',
      justifyContent: 'center',
    },
    infoCancelText: {
      ...Fonts.medium14,
      color: colors.grayColor,
    },
    infoConfirmButton: {
      flex: 1,
      height: 46,
      borderRadius: 10,
      backgroundColor: colors.primaryColor,
      alignItems: 'center',
      justifyContent: 'center',
    },
    infoConfirmText: {
      ...Fonts.medium14,
      color: colors.pureWhite,
    },
  });
